# Run configs
set ::env(PDK_ROOT) {/home/hosni/GF180/OpenLane/pdks}
set ::env(BASE_SDC_FILE) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/base.sdc}
set ::env(BOTTOM_MARGIN_MULT) {4}
set ::env(CARRY_SELECT_ADDER_MAP) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/csa_map.v}
set ::env(CELLS_LEF) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/lef/gf180mcu_fd_sc_mcu7t5v0.lef}
set ::env(CELL_PAD_EXCLUDE) {gf180mcu_fd_sc_mcu7t5v0__filltie_* gf180mcu_fd_sc_mcu7t5v0__filldecap_* gf180mcu_fd_sc_mcu7t5v0__fill_* gf180mcu_fd_sc_mcu7t5v0__endcap_*}
set ::env(CHECK_ASSIGN_STATEMENTS) {0}
set ::env(CHECK_UNMAPPED_CELLS) {1}
set ::env(CLOCK_BUFFER_FANOUT) {16}
set ::env(CLOCK_NET) {wb_clk_i csclk mgmt_gpio_in[4]}
set ::env(CLOCK_PERIOD) {10.0}
set ::env(CLOCK_PORT) {}
set ::env(CLOCK_TREE_SYNTH) {1}
set ::env(CLOCK_WIRE_RC_LAYER) {Metal4}
set ::env(CONFIGS) {general.tcl checkers.tcl synthesis.tcl floorplan.tcl cts.tcl placement.tcl routing.tcl extraction.tcl}
set ::env(CTS_CLK_BUFFER_LIST) {gf180mcu_fd_sc_mcu7t5v0__clkbuf_2 gf180mcu_fd_sc_mcu7t5v0__clkbuf_4 gf180mcu_fd_sc_mcu7t5v0__clkbuf_8}
set ::env(CTS_CLK_MAX_WIRE_LENGTH) {0}
set ::env(CTS_DISABLE_POST_PROCESSING) {0}
set ::env(CTS_DISTANCE_BETWEEN_BUFFERS) {0}
set ::env(CTS_MAX_CAP) {0.2}
set ::env(CTS_REPORT_TIMING) {1}
set ::env(CTS_ROOT_BUFFER) {gf180mcu_fd_sc_mcu7t5v0__clkbuf_16}
set ::env(CTS_SINK_CLUSTERING_MAX_DIAMETER) {50}
set ::env(CTS_SINK_CLUSTERING_SIZE) {25}
set ::env(CTS_TARGET_SKEW) {200}
set ::env(CTS_TOLERANCE) {100}
set ::env(DATA_WIRE_RC_LAYER) {Metal2}
set ::env(DECAP_CELL) {gf180mcu_fd_sc_mcu7t5v0__fillcap_*}
set ::env(DEFAULT_MAX_TRAN) {3}
set ::env(DEF_UNITS_PER_MICRON) {2000}
set ::env(DESIGN_CONFIG) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/config.tcl}
set ::env(DESIGN_IS_CORE) {1}
set ::env(DESIGN_NAME) {housekeeping}
set ::env(DETAILED_ROUTER) {tritonroute}
set ::env(DIE_AREA) {0 0 520 780}
set ::env(DIODE_CELL) {gf180mcu_fd_sc_mcu7t5v0__antenna}
set ::env(DIODE_CELL_PIN) {I}
set ::env(DIODE_INSERTION_STRATEGY) {3}
set ::env(DIODE_PADDING) {0}
set ::env(DPL_CELL_PADDING) {2}
set ::env(DRC_EXCLUDE_CELL_LIST) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/drc_exclude.cells}
set ::env(DRC_EXCLUDE_CELL_LIST_OPT) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/drc_exclude.cells}
set ::env(DRT_MIN_LAYER) {Metal1}
set ::env(DRT_OPT_ITERS) {26}
set ::env(ECO_ENABLE) {0}
set ::env(ECO_FINISH) {0}
set ::env(ECO_ITER) {0}
set ::env(ECO_SKIP_PIN) {1}
set ::env(FILL_CELL) {gf180mcu_fd_sc_mcu7t5v0__fill_*}
set ::env(FP_ASPECT_RATIO) {1}
set ::env(FP_CORE_UTIL) {50}
set ::env(FP_ENDCAP_CELL) {gf180mcu_fd_sc_mcu7t5v0__endcap}
set ::env(FP_IO_HEXTEND) {-1}
set ::env(FP_IO_HLAYER) {Metal3}
set ::env(FP_IO_HLENGTH) {4}
set ::env(FP_IO_HTHICKNESS_MULT) {2}
set ::env(FP_IO_MIN_DISTANCE) {2}
set ::env(FP_IO_MODE) {1}
set ::env(FP_IO_UNMATCHED_ERROR) {1}
set ::env(FP_IO_VEXTEND) {-1}
set ::env(FP_IO_VLAYER) {Metal2}
set ::env(FP_IO_VLENGTH) {4}
set ::env(FP_IO_VTHICKNESS_MULT) {2}
set ::env(FP_PDN_AUTO_ADJUST) {1}
set ::env(FP_PDN_CHECK_NODES) {1}
set ::env(FP_PDN_CORE_RING) {1}
set ::env(FP_PDN_CORE_RING_HOFFSET) {6}
set ::env(FP_PDN_CORE_RING_HSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_HWIDTH) {1.6}
set ::env(FP_PDN_CORE_RING_VOFFSET) {6}
set ::env(FP_PDN_CORE_RING_VSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_VWIDTH) {1.6}
set ::env(FP_PDN_ENABLE_GLOBAL_CONNECTIONS) {1}
set ::env(FP_PDN_ENABLE_MACROS_GRID) {1}
set ::env(FP_PDN_ENABLE_RAILS) {1}
set ::env(FP_PDN_HOFFSET) {16.41}
set ::env(FP_PDN_HORIZONTAL_HALO) {10}
set ::env(FP_PDN_HPITCH) {78.2}
set ::env(FP_PDN_HSPACING) {37.5}
set ::env(FP_PDN_HWIDTH) {1.6}
set ::env(FP_PDN_IRDROP) {1}
set ::env(FP_PDN_LOWER_LAYER) {Metal4}
set ::env(FP_PDN_RAILS_LAYER) {Metal1}
set ::env(FP_PDN_RAIL_OFFSET) {0}
set ::env(FP_PDN_RAIL_WIDTH) {0.6}
set ::env(FP_PDN_SKIPTRIM) {0}
set ::env(FP_PDN_UPPER_LAYER) {Metal5}
set ::env(FP_PDN_VERTICAL_HALO) {10}
set ::env(FP_PDN_VOFFSET) {16.32}
set ::env(FP_PDN_VPITCH) {76.8}
set ::env(FP_PDN_VSPACING) {1.7}
set ::env(FP_PDN_VWIDTH) {1.6}
set ::env(FP_PIN_ORDER_CFG) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/pin_order.cfg}
set ::env(FP_SIZING) {absolute}
set ::env(FP_TAPCELL_DIST) {20}
set ::env(FP_TAP_HORIZONTAL_HALO) {10}
set ::env(FP_TAP_VERTICAL_HALO) {10}
set ::env(FP_WELLTAP_CELL) {gf180mcu_fd_sc_mcu7t5v0__filltie}
set ::env(FULL_ADDER_MAP) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/fa_map.v}
set ::env(GDS_FILES) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/gds/gf180mcu_fd_sc_mcu7t5v0.gds}
set ::env(GENERATE_FINAL_SUMMARY_REPORT) {1}
set ::env(GLB_ADJUSTMENT) {0.2}
set ::env(GLB_CFG_FILE) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/config.tcl}
set ::env(GLB_OPTIMIZE_MIRRORING) {1}
set ::env(GLB_OVERFLOW_ITERS) {100}
set ::env(GLB_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(GLB_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_HOLD_SLACK_MARGIN) {0.05}
set ::env(GLB_RESIZER_MAX_CAP_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_SLEW_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(GLB_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_SETUP_SLACK_MARGIN) {0.1}
set ::env(GLB_RESIZER_TIMING_OPTIMIZATIONS) {1}
set ::env(GLOBAL_ROUTER) {fastroute}
set ::env(GND_PIN) {VSS}
set ::env(GPIO_PADS_LEF) { /home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_io/lef/GF018green_ipio_5p0c_75_5lm.lef
}
set ::env(GPIO_PADS_VERILOG) { /home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_io/verilog/GF018green_ipio_5p0c_75_5lm.v
}
set ::env(GPL_CELL_PADDING) {0}
set ::env(GRT_ADJUSTMENT) {0.3}
set ::env(GRT_ALLOW_CONGESTION) {1}
set ::env(GRT_ANT_ITERS) {10}
set ::env(GRT_ESTIMATE_PARASITICS) {1}
set ::env(GRT_LAYER_ADJUSTMENTS) {0,0,0,0,0}
set ::env(GRT_MACRO_EXTENSION) {0}
set ::env(GRT_MAX_DIODE_INS_ITERS) {10}
set ::env(GRT_OVERFLOW_ITERS) {50}
set ::env(IO_PCT) {0.2}
set ::env(KLAYOUT_DRC_KLAYOUT_GDS) {0}
set ::env(KLAYOUT_DRC_TECH_SCRIPT) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/klayout/gf180mcuC_mr.drc}
set ::env(KLAYOUT_PROPERTIES) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/klayout/gf180mcuC.lyp}
set ::env(KLAYOUT_TECH) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/klayout/gf180mcuC.lyt}
set ::env(KLAYOUT_XOR_GDS) {1}
set ::env(KLAYOUT_XOR_XML) {1}
set ::env(LEC_ENABLE) {0}
set ::env(LEFT_MARGIN_MULT) {12}
set ::env(LIB_FASTEST) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/liberty/gf180mcu_fd_sc_mcu7t5v0__ff_n40C_5v50.lib}
set ::env(LIB_SLOWEST) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/liberty/gf180mcu_fd_sc_mcu7t5v0__ss_125C_4v50.lib}
set ::env(LIB_SYNTH) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/liberty/gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00.lib}
set ::env(LIB_TYPICAL) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/liberty/gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00.lib}
set ::env(LOGS_DIR) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/logs}
set ::env(LVS_CONNECT_BY_LABEL) {0}
set ::env(LVS_INSERT_POWER_PINS) {1}
set ::env(MACRO_BLOCKAGES_LAYER) {Metal1 Metal2 Metal3 Metal4 Metal5}
set ::env(MAGIC_CONVERT_DRC_TO_RDB) {1}
set ::env(MAGIC_DEF_LABELS) {0}
set ::env(MAGIC_DEF_NO_BLOCKAGES) {1}
set ::env(MAGIC_DISABLE_HIER_GDS) {1}
set ::env(MAGIC_DRC_USE_GDS) {1}
set ::env(MAGIC_EXT_USE_GDS) {0}
set ::env(MAGIC_GENERATE_GDS) {1}
set ::env(MAGIC_GENERATE_LEF) {1}
set ::env(MAGIC_GENERATE_MAGLEF) {1}
set ::env(MAGIC_INCLUDE_GDS_POINTERS) {0}
set ::env(MAGIC_MAGICRC) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/magic/gf180mcuC.magicrc}
set ::env(MAGIC_PAD) {0}
set ::env(MAGIC_TECH_FILE) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/magic/gf180mcuC.tech}
set ::env(MAGIC_WRITE_FULL_LEF) {0}
set ::env(MAGIC_ZEROIZE_ORIGIN) {0}
set ::env(METAL_LAYER_NAMES) {Metal1 Metal2 Metal3 Metal4 Metal5}
set ::env(NETGEN_SETUP_FILE) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/netgen/gf180mcuC_setup.tcl}
set ::env(NO_SYNTH_CELL_LIST) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/no_synth.cells}
set ::env(OPENLANE_VERBOSE) {1}
set ::env(PDKPATH) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC}
set ::env(PDN_CFG) {/openlane/scripts/openroad/common/pdn_cfg.tcl}
set ::env(PLACE_SITE) {GF018hv5v_mcu_sc7}
set ::env(PLACE_SITE_HEIGHT) {3.92}
set ::env(PLACE_SITE_WIDTH) {0.56}
set ::env(PL_BASIC_PLACEMENT) {0}
set ::env(PL_ESTIMATE_PARASITICS) {1}
set ::env(PL_LIB) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/liberty/gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00.lib}
set ::env(PL_MACRO_CHANNEL) {0 0}
set ::env(PL_MACRO_HALO) {0 0}
set ::env(PL_MAX_DISPLACEMENT_X) {500}
set ::env(PL_MAX_DISPLACEMENT_Y) {100}
set ::env(PL_OPTIMIZE_MIRRORING) {1}
set ::env(PL_RANDOM_GLB_PLACEMENT) {0}
set ::env(PL_RANDOM_INITIAL_PLACEMENT) {0}
set ::env(PL_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(PL_RESIZER_BUFFER_INPUT_PORTS) {1}
set ::env(PL_RESIZER_BUFFER_OUTPUT_PORTS) {1}
set ::env(PL_RESIZER_DESIGN_OPTIMIZATIONS) {1}
set ::env(PL_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_HOLD_SLACK_MARGIN) {0.1}
set ::env(PL_RESIZER_MAX_CAP_MARGIN) {10}
set ::env(PL_RESIZER_MAX_SLEW_MARGIN) {10}
set ::env(PL_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(PL_RESIZER_REPAIR_TIE_FANOUT) {1}
set ::env(PL_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_SETUP_SLACK_MARGIN) {0.05}
set ::env(PL_RESIZER_TIE_SEPERATION) {0}
set ::env(PL_RESIZER_TIMING_OPTIMIZATIONS) {1}
set ::env(PL_ROUTABILITY_DRIVEN) {1}
set ::env(PL_SKIP_INITIAL_PLACEMENT) {0}
set ::env(PL_TARGET_DENSITY) {0.34}
set ::env(PL_TIME_DRIVEN) {1}
set ::env(PRIMARY_SIGNOFF_TOOL) {magic}
set ::env(PROCESS) {180}
set ::env(QUIT_ON_HOLD_VIOLATIONS) {1}
set ::env(QUIT_ON_ILLEGAL_OVERLAPS) {1}
set ::env(QUIT_ON_LONG_WIRE) {0}
set ::env(QUIT_ON_LVS_ERROR) {1}
set ::env(QUIT_ON_MAGIC_DRC) {1}
set ::env(QUIT_ON_SETUP_VIOLATIONS) {1}
set ::env(QUIT_ON_TIMING_VIOLATIONS) {1}
set ::env(QUIT_ON_TR_DRC) {1}
set ::env(RCX_CC_MODEL) {10}
set ::env(RCX_CONTEXT_DEPTH) {5}
set ::env(RCX_CORNER_COUNT) {1}
set ::env(RCX_COUPLING_THRESHOLD) {0.1}
set ::env(RCX_MAX_RESISTANCE) {50}
set ::env(RCX_MERGE_VIA_WIRE_RES) {1}
set ::env(RCX_RULES) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/RCnom.rules}
set ::env(RCX_RULES_MAX) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/rules.openrcx.gf180mcuC.max.magic}
set ::env(RCX_RULES_MIN) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/rules.openrcx.gf180mcuC.min.magic}
set ::env(RCX_SDC_FILE) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/signoff.sdc}
set ::env(REPORTS_DIR) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports}
set ::env(RESULTS_DIR) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results}
set ::env(RIGHT_MARGIN_MULT) {12}
set ::env(RIPPLE_CARRY_ADDER_MAP) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/rca_map.v}
set ::env(ROUTING_CORES) {12}
set ::env(RSZ_DONT_TOUCH_RX) {$^}
set ::env(RSZ_USE_OLD_REMOVER) {0}
set ::env(RT_MAX_LAYER) {Metal5}
set ::env(RT_MIN_LAYER) {Metal2}
set ::env(RUN_CVC) {1}
set ::env(RUN_DIR) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22}
set ::env(RUN_DRT) {1}
set ::env(RUN_FILL_INSERTION) {1}
set ::env(RUN_IRDROP_REPORT) {0}
set ::env(RUN_KLAYOUT) {0}
set ::env(RUN_KLAYOUT_DRC) {0}
set ::env(RUN_KLAYOUT_XOR) {0}
set ::env(RUN_LVS) {1}
set ::env(RUN_MAGIC) {1}
set ::env(RUN_MAGIC_DRC) {1}
set ::env(RUN_SPEF_EXTRACTION) {1}
set ::env(RUN_TAG) {RUN_2022.11.19_02.10.22}
set ::env(RUN_TAP_DECAP_INSERTION) {1}
set ::env(SCLPATH) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/gf180mcu_fd_sc_mcu7t5v0}
set ::env(SPEF_EXTRACTOR) {openrcx}
set ::env(START_TIME) {2022.11.19_02.10.22}
set ::env(STA_REPORT_POWER) {1}
set ::env(STA_WRITE_LIB) {0}
set ::env(STD_CELL_GROUND_PINS) {VSS}
set ::env(STD_CELL_LIBRARY) {gf180mcu_fd_sc_mcu7t5v0}
set ::env(STD_CELL_LIBRARY_CDL) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/cdl/gf180mcu_fd_sc_mcu7t5v0.cdl}
set ::env(STD_CELL_LIBRARY_OPT) {gf180mcu_fd_sc_mcu7t5v0}
set ::env(STD_CELL_POWER_PINS) {VDD}
set ::env(SYNTH_ADDER_TYPE) {YOSYS}
set ::env(SYNTH_BIN) {yosys}
set ::env(SYNTH_BUFFERING) {0}
set ::env(SYNTH_CAP_LOAD) {72.91}
set ::env(SYNTH_CLK_DRIVING_CELL) {gf180mcu_fd_sc_mcu7t5v0__inv_4}
set ::env(SYNTH_CLK_DRIVING_CELL_PIN) {ZN}
set ::env(SYNTH_CLOCK_TRANSITION) {0.15}
set ::env(SYNTH_CLOCK_UNCERTAINTY) {0.25}
set ::env(SYNTH_DRIVING_CELL) {gf180mcu_fd_sc_mcu7t5v0__inv_1}
set ::env(SYNTH_DRIVING_CELL_PIN) {ZN}
set ::env(SYNTH_ELABORATE_ONLY) {0}
set ::env(SYNTH_EXTRA_MAPPING_FILE) {}
set ::env(SYNTH_FLAT_TOP) {0}
set ::env(SYNTH_LATCH_MAP) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/latch_map.v}
set ::env(SYNTH_MAX_FANOUT) {20}
set ::env(SYNTH_MIN_BUF_PORT) {gf180mcu_fd_sc_mcu7t5v0__buf_1 I Z}
set ::env(SYNTH_NO_FLAT) {0}
set ::env(SYNTH_READ_BLACKBOX_LIB) {1}
set ::env(SYNTH_SCRIPT) {/openlane/scripts/yosys/synth.tcl}
set ::env(SYNTH_SHARE_RESOURCES) {1}
set ::env(SYNTH_SIZING) {0}
set ::env(SYNTH_STRATEGY) {DELAY 0}
set ::env(SYNTH_TIEHI_PORT) {gf180mcu_fd_sc_mcu7t5v0__tieh Z}
set ::env(SYNTH_TIELO_PORT) {gf180mcu_fd_sc_mcu7t5v0__tiel ZN}
set ::env(SYNTH_TIMING_DERATE) {0.05}
set ::env(TAKE_LAYOUT_SCROT) {0}
set ::env(TECH_LEF) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/techlef/gf180mcu_fd_sc_mcu7t5v0.tlef}
set ::env(TERMINAL_OUTPUT) {/dev/null}
set ::env(TMP_DIR) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp}
set ::env(TOP_MARGIN_MULT) {4}
set ::env(TRACKS_INFO_FILE) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/tracks.info}
set ::env(TRISTATE_BUFFER_MAP) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/tribuff_map.v}
set ::env(USE_ARC_ANTENNA_CHECK) {1}
set ::env(USE_GPIO_PADS) {0}
set ::env(VDD_PIN) {VDD}
set ::env(VERILOG_FILES) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/../../verilog/rtl/defines.v  /home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/../../verilog/rtl/housekeeping.v  /home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/../../verilog/rtl/housekeeping_spi.v}
set ::env(WIRE_RC_LAYER) {Metal2}
set ::env(YOSYS_REWRITE_VERILOG) {0}
set ::env(cts_logs) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/logs/cts}
set ::env(cts_reports) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/cts}
set ::env(cts_results) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/cts}
set ::env(cts_tmpfiles) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/cts}
set ::env(eco_logs) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/logs/eco}
set ::env(eco_reports) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/eco}
set ::env(eco_results) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/eco}
set ::env(eco_tmpfiles) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/eco}
set ::env(floorplan_logs) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/logs/floorplan}
set ::env(floorplan_reports) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/floorplan}
set ::env(floorplan_results) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/floorplan}
set ::env(floorplan_tmpfiles) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/floorplan}
set ::env(placement_logs) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/logs/placement}
set ::env(placement_reports) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/placement}
set ::env(placement_results) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/placement}
set ::env(placement_tmpfiles) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/placement}
set ::env(routing_logs) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/logs/routing}
set ::env(routing_reports) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/routing}
set ::env(routing_results) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/routing}
set ::env(routing_tmpfiles) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/routing}
set ::env(signoff_logs) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/logs/signoff}
set ::env(signoff_reports) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/signoff}
set ::env(signoff_results) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/signoff}
set ::env(signoff_tmpfiles) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/signoff}
set ::env(synthesis_logs) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/logs/synthesis}
set ::env(synthesis_reports) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/synthesis}
set ::env(synthesis_results) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/synthesis}
set ::env(synthesis_tmpfiles) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/synthesis}
set ::env(SYNTH_MAX_TRAN) {1.0}
set ::env(CURRENT_INDEX) 28
set ::env(CURRENT_DEF) /home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/routing/housekeeping.def
set ::env(CURRENT_GUIDE) /home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/routing/14-global.guide
set ::env(CURRENT_NETLIST) /home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/signoff/24-housekeeping.nl.v
set ::env(CURRENT_POWERED_NETLIST) {0}
set ::env(CURRENT_ODB) /home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/routing/housekeeping.odb
set ::env(PDK_ROOT) {/home/hosni/GF180/OpenLane/pdks}
set ::env(ANTENNA_CHECK_CURRENT_DEF) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/routing/housekeeping.def}
set ::env(ANTENNA_VIOLATOR_LIST) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/signoff/22-antenna_violators.rpt}
set ::env(BASE_SDC_FILE) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/base.sdc}
set ::env(BASIC_PREP_COMPLETE) {1}
set ::env(BOTTOM_MARGIN_MULT) {4}
set ::env(CARAVEL_ROOT) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/../..}
set ::env(CARRY_SELECT_ADDER_MAP) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/csa_map.v}
set ::env(CELLS_LEF) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/lef/gf180mcu_fd_sc_mcu7t5v0.lef}
set ::env(CELL_PAD_EXCLUDE) {gf180mcu_fd_sc_mcu7t5v0__filltie_* gf180mcu_fd_sc_mcu7t5v0__filldecap_* gf180mcu_fd_sc_mcu7t5v0__fill_* gf180mcu_fd_sc_mcu7t5v0__endcap_*}
set ::env(CHECK_ASSIGN_STATEMENTS) {0}
set ::env(CHECK_UNMAPPED_CELLS) {1}
set ::env(CLOCK_BUFFER_FANOUT) {16}
set ::env(CLOCK_NET) {wb_clk_i csclk mgmt_gpio_in[4]}
set ::env(CLOCK_PERIOD) {10.0}
set ::env(CLOCK_PORT) {}
set ::env(CLOCK_TREE_SYNTH) {1}
set ::env(CLOCK_WIRE_RC_LAYER) {Metal4}
set ::env(CONFIGS) {general.tcl checkers.tcl synthesis.tcl floorplan.tcl cts.tcl placement.tcl routing.tcl extraction.tcl}
set ::env(CORE_AREA) {6.72 15.68 512.96 760.48}
set ::env(CORE_HEIGHT) {744.8}
set ::env(CORE_WIDTH) {506.24}
set ::env(CTS_CLK_BUFFER_LIST) {gf180mcu_fd_sc_mcu7t5v0__clkbuf_2 gf180mcu_fd_sc_mcu7t5v0__clkbuf_4 gf180mcu_fd_sc_mcu7t5v0__clkbuf_8}
set ::env(CTS_CLK_MAX_WIRE_LENGTH) {0}
set ::env(CTS_CURRENT_DEF) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/placement/housekeeping.def}
set ::env(CTS_DISABLE_POST_PROCESSING) {0}
set ::env(CTS_DISTANCE_BETWEEN_BUFFERS) {0}
set ::env(CTS_MAX_CAP) {0.2}
set ::env(CTS_REPORT_TIMING) {1}
set ::env(CTS_ROOT_BUFFER) {gf180mcu_fd_sc_mcu7t5v0__clkbuf_16}
set ::env(CTS_SINK_CLUSTERING_MAX_DIAMETER) {50}
set ::env(CTS_SINK_CLUSTERING_SIZE) {25}
set ::env(CTS_TARGET_SKEW) {200}
set ::env(CTS_TOLERANCE) {100}
set ::env(CURRENT_DEF) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/signoff/24-housekeeping.p.def}
set ::env(CURRENT_DIR) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/routing}
set ::env(CURRENT_GDS) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/signoff/housekeeping.gds}
set ::env(CURRENT_GUIDE) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/routing/14-global.guide}
set ::env(CURRENT_INDEX) {28}
set ::env(CURRENT_NETLIST) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/signoff/24-housekeeping.nl.v}
set ::env(CURRENT_ODB) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/routing/housekeeping.odb}
set ::env(CURRENT_POWERED_NETLIST) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/signoff/24-housekeeping.pnl.v}
set ::env(CURRENT_SDC) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/12-housekeeping.sdc}
set ::env(CURRENT_SDF) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/routing/mca/process_corner_nom/housekeeping.sdf}
set ::env(CURRENT_SPEF) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/routing/mca/process_corner_nom/housekeeping.spef}
set ::env(CURRENT_STEP) {}
set ::env(DATA_WIRE_RC_LAYER) {Metal2}
set ::env(DECAP_CELL) {gf180mcu_fd_sc_mcu7t5v0__fillcap_*}
set ::env(DEFAULT_MAX_TRAN) {3}
set ::env(DEF_UNITS_PER_MICRON) {2000}
set ::env(DESIGN_CONFIG) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/config.tcl}
set ::env(DESIGN_DIR) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping}
set ::env(DESIGN_IS_CORE) {1}
set ::env(DESIGN_NAME) {housekeeping}
set ::env(DETAILED_ROUTER) {tritonroute}
set ::env(DIE_AREA) {0.0 0.0 520.0 780.0}
set ::env(DIODE_CELL) {gf180mcu_fd_sc_mcu7t5v0__antenna}
set ::env(DIODE_CELL_PIN) {I}
set ::env(DIODE_INSERTION_CURRENT_DEF) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/routing/housekeeping.def}
set ::env(DIODE_INSERTION_STRATEGY) {3}
set ::env(DIODE_PADDING) {0}
set ::env(DONT_USE_CELLS) {gf180mcu_fd_sc_mcu7t5v0__mux2_1 gf180mcu_fd_sc_mcu7t5v0__oai33_2 }
set ::env(DPL_CELL_PADDING) {2}
set ::env(DRC_CURRENT_DEF) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/signoff/24-housekeeping.p.def}
set ::env(DRC_EXCLUDE_CELL_LIST) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/drc_exclude.cells}
set ::env(DRC_EXCLUDE_CELL_LIST_OPT) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/drc_exclude.cells}
set ::env(DRT_MIN_LAYER) {Metal1}
set ::env(DRT_OPT_ITERS) {26}
set ::env(ECO_ENABLE) {0}
set ::env(ECO_FINISH) {0}
set ::env(ECO_ITER) {0}
set ::env(ECO_SKIP_PIN) {1}
set ::env(EXT_NETLIST) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/signoff/housekeeping.spice}
set ::env(FILL_CELL) {gf180mcu_fd_sc_mcu7t5v0__fill_*}
set ::env(FP_ASPECT_RATIO) {1}
set ::env(FP_CORE_UTIL) {50}
set ::env(FP_ENDCAP_CELL) {gf180mcu_fd_sc_mcu7t5v0__endcap}
set ::env(FP_IO_HEXTEND) {-1}
set ::env(FP_IO_HLAYER) {Metal3}
set ::env(FP_IO_HLENGTH) {4}
set ::env(FP_IO_HTHICKNESS_MULT) {2}
set ::env(FP_IO_MIN_DISTANCE) {2}
set ::env(FP_IO_MODE) {1}
set ::env(FP_IO_UNMATCHED_ERROR) {1}
set ::env(FP_IO_VEXTEND) {-1}
set ::env(FP_IO_VLAYER) {Metal2}
set ::env(FP_IO_VLENGTH) {4}
set ::env(FP_IO_VTHICKNESS_MULT) {2}
set ::env(FP_PDN_AUTO_ADJUST) {1}
set ::env(FP_PDN_CHECK_NODES) {1}
set ::env(FP_PDN_CORE_RING) {1}
set ::env(FP_PDN_CORE_RING_HOFFSET) {6}
set ::env(FP_PDN_CORE_RING_HSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_HWIDTH) {1.6}
set ::env(FP_PDN_CORE_RING_VOFFSET) {6}
set ::env(FP_PDN_CORE_RING_VSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_VWIDTH) {1.6}
set ::env(FP_PDN_ENABLE_GLOBAL_CONNECTIONS) {1}
set ::env(FP_PDN_ENABLE_MACROS_GRID) {1}
set ::env(FP_PDN_ENABLE_RAILS) {1}
set ::env(FP_PDN_HOFFSET) {16.41}
set ::env(FP_PDN_HORIZONTAL_HALO) {10}
set ::env(FP_PDN_HPITCH) {78.2}
set ::env(FP_PDN_HSPACING) {37.5}
set ::env(FP_PDN_HWIDTH) {1.6}
set ::env(FP_PDN_IRDROP) {1}
set ::env(FP_PDN_LOWER_LAYER) {Metal4}
set ::env(FP_PDN_RAILS_LAYER) {Metal1}
set ::env(FP_PDN_RAIL_OFFSET) {0}
set ::env(FP_PDN_RAIL_WIDTH) {0.6}
set ::env(FP_PDN_SKIPTRIM) {0}
set ::env(FP_PDN_UPPER_LAYER) {Metal5}
set ::env(FP_PDN_VERTICAL_HALO) {10}
set ::env(FP_PDN_VOFFSET) {16.32}
set ::env(FP_PDN_VPITCH) {76.8}
set ::env(FP_PDN_VSPACING) {1.7}
set ::env(FP_PDN_VWIDTH) {1.6}
set ::env(FP_PIN_ORDER_CFG) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/pin_order.cfg}
set ::env(FP_SIZING) {absolute}
set ::env(FP_TAPCELL_DIST) {20}
set ::env(FP_TAP_HORIZONTAL_HALO) {10}
set ::env(FP_TAP_VERTICAL_HALO) {10}
set ::env(FP_WELLTAP_CELL) {gf180mcu_fd_sc_mcu7t5v0__filltie}
set ::env(FULL_ADDER_MAP) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/fa_map.v}
set ::env(GDS_FILES) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/gds/gf180mcu_fd_sc_mcu7t5v0.gds}
set ::env(GENERATE_FINAL_SUMMARY_REPORT) {1}
set ::env(GLB_ADJUSTMENT) {0.2}
set ::env(GLB_CFG_FILE) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/config.tcl}
set ::env(GLB_OPTIMIZE_MIRRORING) {1}
set ::env(GLB_OVERFLOW_ITERS) {100}
set ::env(GLB_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(GLB_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_HOLD_SLACK_MARGIN) {0.05}
set ::env(GLB_RESIZER_MAX_CAP_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_SLEW_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(GLB_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_SETUP_SLACK_MARGIN) {0.1}
set ::env(GLB_RESIZER_TIMING_OPTIMIZATIONS) {1}
set ::env(GLOBAL_ROUTER) {fastroute}
set ::env(GND_NET) {VSS}
set ::env(GND_NETS) {VSS}
set ::env(GND_PIN) {VSS}
set ::env(GPIO_PADS_LEF) { /home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_io/lef/GF018green_ipio_5p0c_75_5lm.lef
}
set ::env(GPIO_PADS_VERILOG) { /home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_io/verilog/GF018green_ipio_5p0c_75_5lm.v
}
set ::env(GPL_CELL_PADDING) {0}
set ::env(GRT_ADJUSTMENT) {0.3}
set ::env(GRT_ALLOW_CONGESTION) {1}
set ::env(GRT_ANT_ITERS) {10}
set ::env(GRT_ESTIMATE_PARASITICS) {1}
set ::env(GRT_LAYER_ADJUSTMENTS) {0,0,0,0,0}
set ::env(GRT_MACRO_EXTENSION) {0}
set ::env(GRT_MAX_DIODE_INS_ITERS) {10}
set ::env(GRT_OVERFLOW_ITERS) {50}
set ::env(HOME) {/}
set ::env(HOSTNAME) {4c27792c4f49}
set ::env(IO_PCT) {0.2}
set ::env(KLAYOUT_DRC_KLAYOUT_GDS) {0}
set ::env(KLAYOUT_DRC_TECH_SCRIPT) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/klayout/gf180mcuC_mr.drc}
set ::env(KLAYOUT_PROPERTIES) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/klayout/gf180mcuC.lyp}
set ::env(KLAYOUT_TECH) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/klayout/gf180mcuC.lyt}
set ::env(KLAYOUT_XOR_GDS) {1}
set ::env(KLAYOUT_XOR_XML) {1}
set ::env(LANG) {en_US.UTF-8}
set ::env(LAST_TIMING_REPORT_TAG) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/signoff/21-rcx_sta}
set ::env(LC_ALL) {en_US.UTF-8}
set ::env(LC_CTYPE) {en_US.UTF-8}
set ::env(LD_LIBRARY_PATH) {/build//lib:/build//lib/Linux-x86_64:}
set ::env(LEC_ENABLE) {0}
set ::env(LEFT_MARGIN_MULT) {12}
set ::env(LIB_CTS) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/cts/cts.lib}
set ::env(LIB_FASTEST) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/liberty/gf180mcu_fd_sc_mcu7t5v0__ff_n40C_5v50.lib}
set ::env(LIB_SLOWEST) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/liberty/gf180mcu_fd_sc_mcu7t5v0__ss_125C_4v50.lib}
set ::env(LIB_SYNTH) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/synthesis/trimmed.lib}
set ::env(LIB_SYNTH_COMPLETE) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/liberty/gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00.lib}
set ::env(LIB_SYNTH_COMPLETE_NO_PG) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/synthesis/1-gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00.no_pg.lib}
set ::env(LIB_SYNTH_MERGED) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/synthesis/merged.lib}
set ::env(LIB_SYNTH_NO_PG) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/synthesis/1-trimmed.no_pg.lib}
set ::env(LIB_TYPICAL) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/liberty/gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00.lib}
set ::env(LOGS_DIR) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/logs}
set ::env(LVS_CONNECT_BY_LABEL) {0}
set ::env(LVS_CURRENT_DEF) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/routing/housekeeping.def}
set ::env(LVS_INSERT_POWER_PINS) {1}
set ::env(MACRO_BLOCKAGES_LAYER) {Metal1 Metal2 Metal3 Metal4 Metal5}
set ::env(MAGIC_CONVERT_DRC_TO_RDB) {1}
set ::env(MAGIC_DEF_LABELS) {0}
set ::env(MAGIC_DEF_NO_BLOCKAGES) {1}
set ::env(MAGIC_DISABLE_HIER_GDS) {1}
set ::env(MAGIC_DRC_USE_GDS) {1}
set ::env(MAGIC_EXT_USE_GDS) {0}
set ::env(MAGIC_GDS) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/signoff/housekeeping.magic.gds}
set ::env(MAGIC_GENERATE_GDS) {1}
set ::env(MAGIC_GENERATE_LEF) {1}
set ::env(MAGIC_GENERATE_MAGLEF) {1}
set ::env(MAGIC_INCLUDE_GDS_POINTERS) {0}
set ::env(MAGIC_MAGICRC) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/magic/gf180mcuC.magicrc}
set ::env(MAGIC_PAD) {0}
set ::env(MAGIC_TECH_FILE) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/magic/gf180mcuC.tech}
set ::env(MAGIC_WRITE_FULL_LEF) {0}
set ::env(MAGIC_ZEROIZE_ORIGIN) {0}
set ::env(MAGTYPE) {maglef}
set ::env(MANPATH) {/build//share/man:}
set ::env(MAX_METAL_LAYER) {5}
set ::env(MCW_ROOT) {/home/hosni/GF180/caravel_mgmt_soc_gf180mcu}
set ::env(MC_SDF_DIR) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/routing/mca/sdf}
set ::env(MC_SPEF_DIR) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/routing/mca/spef}
set ::env(MERGED_LEF) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/merged.nom.lef}
set ::env(METAL_LAYER_NAMES) {Metal1 Metal2 Metal3 Metal4 Metal5}
set ::env(MISMATCHES_OK) {1}
set ::env(NETGEN_SETUP_FILE) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/netgen/gf180mcuC_setup.tcl}
set ::env(NO_SYNTH_CELL_LIST) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/no_synth.cells}
set ::env(OPENLANE_ROOT) {/openlane}
set ::env(OPENLANE_RUN_TAG) {22_11_18_18_10}
set ::env(OPENLANE_VERBOSE) {1}
set ::env(OPENLANE_VERSION) {1298859773c026fc1e852b2727ccd7c26d96e7bb}
set ::env(OPENROAD) {/build/}
set ::env(OPENROAD_BIN) {openroad}
set ::env(PARSITICS_CURRENT_DEF) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/routing/housekeeping.def}
set ::env(PATH) {/openlane:/openlane/scripts:/build//bin:/build//bin/Linux-x86_64:/build//pdn/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin}
set ::env(PDK) {gf180mcuC}
set ::env(PDKPATH) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC}
set ::env(PDK_ROOT) {/home/hosni/GF180/OpenLane/pdks}
set ::env(PDN_CFG) {/openlane/scripts/openroad/common/pdn_cfg.tcl}
set ::env(PLACEMENT_CURRENT_DEF) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/floorplan/6-pdn.def}
set ::env(PLACE_SITE) {GF018hv5v_mcu_sc7}
set ::env(PLACE_SITE_HEIGHT) {3.92}
set ::env(PLACE_SITE_WIDTH) {0.56}
set ::env(PL_BASIC_PLACEMENT) {0}
set ::env(PL_ESTIMATE_PARASITICS) {1}
set ::env(PL_INIT_COEFF) {0.00002}
set ::env(PL_IO_ITER) {5}
set ::env(PL_LIB) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/liberty/gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00.lib}
set ::env(PL_MACRO_CHANNEL) {0 0}
set ::env(PL_MACRO_HALO) {0 0}
set ::env(PL_MAX_DISPLACEMENT_X) {500}
set ::env(PL_MAX_DISPLACEMENT_Y) {100}
set ::env(PL_OPTIMIZE_MIRRORING) {1}
set ::env(PL_RANDOM_GLB_PLACEMENT) {0}
set ::env(PL_RANDOM_INITIAL_PLACEMENT) {0}
set ::env(PL_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(PL_RESIZER_BUFFER_INPUT_PORTS) {1}
set ::env(PL_RESIZER_BUFFER_OUTPUT_PORTS) {1}
set ::env(PL_RESIZER_DESIGN_OPTIMIZATIONS) {1}
set ::env(PL_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_HOLD_SLACK_MARGIN) {0.1}
set ::env(PL_RESIZER_MAX_CAP_MARGIN) {10}
set ::env(PL_RESIZER_MAX_SLEW_MARGIN) {10}
set ::env(PL_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(PL_RESIZER_REPAIR_TIE_FANOUT) {1}
set ::env(PL_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_SETUP_SLACK_MARGIN) {0.05}
set ::env(PL_RESIZER_TIE_SEPERATION) {0}
set ::env(PL_RESIZER_TIMING_OPTIMIZATIONS) {1}
set ::env(PL_ROUTABILITY_DRIVEN) {1}
set ::env(PL_SKIP_INITIAL_PLACEMENT) {0}
set ::env(PL_TARGET_DENSITY) {0.34}
set ::env(PL_TIME_DRIVEN) {1}
set ::env(PRIMARY_SIGNOFF_TOOL) {magic}
set ::env(PROCESS) {180}
set ::env(PWD) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane}
set ::env(QUIT_ON_HOLD_VIOLATIONS) {1}
set ::env(QUIT_ON_ILLEGAL_OVERLAPS) {1}
set ::env(QUIT_ON_LONG_WIRE) {0}
set ::env(QUIT_ON_LVS_ERROR) {1}
set ::env(QUIT_ON_MAGIC_DRC) {1}
set ::env(QUIT_ON_SETUP_VIOLATIONS) {1}
set ::env(QUIT_ON_TIMING_VIOLATIONS) {1}
set ::env(QUIT_ON_TR_DRC) {1}
set ::env(RCX_CC_MODEL) {10}
set ::env(RCX_CONTEXT_DEPTH) {5}
set ::env(RCX_CORNER_COUNT) {1}
set ::env(RCX_COUPLING_THRESHOLD) {0.1}
set ::env(RCX_MAX_RESISTANCE) {50}
set ::env(RCX_MERGE_VIA_WIRE_RES) {1}
set ::env(RCX_RULES) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/RCnom.rules}
set ::env(RCX_RULES_MAX) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/rules.openrcx.gf180mcuC.max.magic}
set ::env(RCX_RULES_MIN) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/rules.openrcx.gf180mcuC.min.magic}
set ::env(RCX_SDC_FILE) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/signoff.sdc}
set ::env(REPORTS_DIR) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports}
set ::env(RESULTS_DIR) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results}
set ::env(RIGHT_MARGIN_MULT) {12}
set ::env(RIPPLE_CARRY_ADDER_MAP) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/rca_map.v}
set ::env(ROUTING_CORES) {12}
set ::env(ROUTING_CURRENT_DEF) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/cts/11-housekeeping.resized.def}
set ::env(RSZ_DONT_TOUCH_RX) {\$^}
set ::env(RSZ_LIB) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/synthesis/resizer_gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00.lib}
set ::env(RSZ_USE_OLD_REMOVER) {0}
set ::env(RT_MAX_LAYER) {Metal5}
set ::env(RT_MIN_LAYER) {Metal2}
set ::env(RUN_CVC) {1}
set ::env(RUN_DIR) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22}
set ::env(RUN_DRT) {1}
set ::env(RUN_FILL_INSERTION) {1}
set ::env(RUN_IRDROP_REPORT) {0}
set ::env(RUN_KLAYOUT) {0}
set ::env(RUN_KLAYOUT_DRC) {0}
set ::env(RUN_KLAYOUT_XOR) {0}
set ::env(RUN_LVS) {1}
set ::env(RUN_MAGIC) {1}
set ::env(RUN_MAGIC_DRC) {1}
set ::env(RUN_SPEF_EXTRACTION) {1}
set ::env(RUN_STANDALONE) {1}
set ::env(RUN_TAG) {RUN_2022.11.19_02.10.22}
set ::env(RUN_TAP_DECAP_INSERTION) {1}
set ::env(SCLPATH) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/gf180mcu_fd_sc_mcu7t5v0}
set ::env(SCRIPTS_DIR) {/openlane/scripts}
set ::env(SHLVL) {1}
set ::env(SPEF_EXTRACTOR) {openrcx}
set ::env(START_TIME) {2022.11.19_02.10.22}
set ::env(STA_PRE_CTS) {0}
set ::env(STA_REPORT_POWER) {1}
set ::env(STA_WRITE_LIB) {0}
set ::env(STD_CELL_GROUND_PINS) {VSS}
set ::env(STD_CELL_LIBRARY) {gf180mcu_fd_sc_mcu7t5v0}
set ::env(STD_CELL_LIBRARY_CDL) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/cdl/gf180mcu_fd_sc_mcu7t5v0.cdl}
set ::env(STD_CELL_LIBRARY_OPT) {gf180mcu_fd_sc_mcu7t5v0}
set ::env(STD_CELL_POWER_PINS) {VDD}
set ::env(SYNTH_ADDER_TYPE) {YOSYS}
set ::env(SYNTH_BIN) {yosys}
set ::env(SYNTH_BUFFERING) {0}
set ::env(SYNTH_CAP_LOAD) {72.91}
set ::env(SYNTH_CLK_DRIVING_CELL) {gf180mcu_fd_sc_mcu7t5v0__inv_4}
set ::env(SYNTH_CLK_DRIVING_CELL_PIN) {ZN}
set ::env(SYNTH_CLOCK_TRANSITION) {0.15}
set ::env(SYNTH_CLOCK_UNCERTAINTY) {0.25}
set ::env(SYNTH_DRIVING_CELL) {gf180mcu_fd_sc_mcu7t5v0__inv_1}
set ::env(SYNTH_DRIVING_CELL_PIN) {ZN}
set ::env(SYNTH_ELABORATE_ONLY) {0}
set ::env(SYNTH_EXTRA_MAPPING_FILE) {}
set ::env(SYNTH_FLAT_TOP) {0}
set ::env(SYNTH_LATCH_MAP) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/latch_map.v}
set ::env(SYNTH_MAX_FANOUT) {20}
set ::env(SYNTH_MAX_TRAN) {1.0}
set ::env(SYNTH_MIN_BUF_PORT) {gf180mcu_fd_sc_mcu7t5v0__buf_1 I Z}
set ::env(SYNTH_NO_FLAT) {0}
set ::env(SYNTH_OPT) {0}
set ::env(SYNTH_READ_BLACKBOX_LIB) {1}
set ::env(SYNTH_SCRIPT) {/openlane/scripts/yosys/synth.tcl}
set ::env(SYNTH_SHARE_RESOURCES) {1}
set ::env(SYNTH_SIZING) {0}
set ::env(SYNTH_STRATEGY) {DELAY 0}
set ::env(SYNTH_TIEHI_PORT) {gf180mcu_fd_sc_mcu7t5v0__tieh Z}
set ::env(SYNTH_TIELO_PORT) {gf180mcu_fd_sc_mcu7t5v0__tiel ZN}
set ::env(SYNTH_TIMING_DERATE) {0.05}
set ::env(TAKE_LAYOUT_SCROT) {0}
set ::env(TECH_LEF) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/techlef/gf180mcu_fd_sc_mcu7t5v0.tlef}
set ::env(TECH_METAL_LAYERS) {Metal1 Metal2 Metal3 Metal4 Metal5}
set ::env(TERM) {xterm}
set ::env(TERMINAL_OUTPUT) {/dev/null}
set ::env(TMP_DIR) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp}
set ::env(TOP_MARGIN_MULT) {4}
set ::env(TRACKS_INFO_FILE) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/tracks.info}
set ::env(TRACKS_INFO_FILE_PROCESSED) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/routing/config.tracks}
set ::env(TRISTATE_BUFFER_MAP) {/home/hosni/GF180/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/tribuff_map.v}
set ::env(USE_ARC_ANTENNA_CHECK) {1}
set ::env(USE_GPIO_PADS) {0}
set ::env(VCHECK_OUTPUT) {}
set ::env(VDD_NET) {VDD}
set ::env(VDD_NETS) {VDD}
set ::env(VDD_PIN) {VDD}
set ::env(VERILOG_FILES) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/../../verilog/rtl/defines.v  /home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/../../verilog/rtl/housekeeping.v  /home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/../../verilog/rtl/housekeeping_spi.v}
set ::env(WIRE_RC_LAYER) {Metal2}
set ::env(YOSYS_REWRITE_VERILOG) {0}
set ::env(_) {/openlane/flow.tcl}
set ::env(cts_logs) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/logs/cts}
set ::env(cts_reports) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/cts}
set ::env(cts_results) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/cts}
set ::env(cts_tmpfiles) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/cts}
set ::env(drc_prefix) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/signoff/drc}
set ::env(eco_logs) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/logs/eco}
set ::env(eco_reports) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/eco}
set ::env(eco_results) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/eco}
set ::env(eco_tmpfiles) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/eco}
set ::env(floorplan_logs) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/logs/floorplan}
set ::env(floorplan_reports) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/floorplan}
set ::env(floorplan_results) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/floorplan}
set ::env(floorplan_tmpfiles) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/floorplan}
set ::env(fp_report_prefix) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/floorplan/3-initial_fp}
set ::env(placement_logs) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/logs/placement}
set ::env(placement_reports) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/placement}
set ::env(placement_results) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/placement}
set ::env(placement_tmpfiles) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/placement}
set ::env(routing_logs) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/logs/routing}
set ::env(routing_reports) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/routing}
set ::env(routing_results) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/routing}
set ::env(routing_tmpfiles) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/routing}
set ::env(signoff_logs) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/logs/signoff}
set ::env(signoff_reports) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/signoff}
set ::env(signoff_results) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/signoff}
set ::env(signoff_tmpfiles) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/signoff}
set ::env(synth_report_prefix) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/synthesis/1-synthesis}
set ::env(synthesis_logs) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/logs/synthesis}
set ::env(synthesis_reports) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/reports/synthesis}
set ::env(synthesis_results) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/results/synthesis}
set ::env(synthesis_tmpfiles) {/home/hosni/GF180/EF/caravel-gf180mcu/openlane/housekeeping/runs/RUN_2022.11.19_02.10.22/tmp/synthesis}
set ::env(timer_end) {1668824110}
set ::env(timer_routed) {1668824001}
set ::env(timer_start) {1668823822}
