/* Generated by Yosys 0.22 (git sha1 f109fa3d4c5, gcc 8.3.1 -fPIC -Os) */

module chip_io(vss, vdd, gpio, clock, resetb, flash_csb, flash_clk, flash_io0, flash_io1, resetb_core, clock_core, gpio_in_core, gpio_out_core, gpio_outen_core, gpio_inen_core, gpio_pu_select, gpio_pd_select, gpio_schmitt_select, gpio_slew_select, gpio_drive_select_core, flash_csb_core
, flash_clk_core, flash_csb_oe_core, flash_clk_oe_core, flash_io0_oe_core, flash_io1_oe_core, flash_io0_ie_core, flash_io1_ie_core, flash_io0_do_core, flash_io1_do_core, flash_io0_di_core, flash_io1_di_core, const_zero, const_one, mprj_io, mprj_io_out, mprj_io_outen, mprj_io_inen, mprj_io_schmitt_select, mprj_io_slew_select, mprj_io_pu_select, mprj_io_pd_select
, mprj_io_drive_sel, mprj_io_in);
  input clock;
  wire clock;
  output clock_core;
  wire clock_core;
  input [1:0] const_one;
  wire [1:0] const_one;
  input [5:0] const_zero;
  wire [5:0] const_zero;
  output flash_clk;
  wire flash_clk;
  input flash_clk_core;
  wire flash_clk_core;
  input flash_clk_oe_core;
  wire flash_clk_oe_core;
  output flash_csb;
  wire flash_csb;
  input flash_csb_core;
  wire flash_csb_core;
  input flash_csb_oe_core;
  wire flash_csb_oe_core;
  inout flash_io0;
  wire flash_io0;
  output flash_io0_di_core;
  wire flash_io0_di_core;
  input flash_io0_do_core;
  wire flash_io0_do_core;
  input flash_io0_ie_core;
  wire flash_io0_ie_core;
  input flash_io0_oe_core;
  wire flash_io0_oe_core;
  inout flash_io1;
  wire flash_io1;
  output flash_io1_di_core;
  wire flash_io1_di_core;
  input flash_io1_do_core;
  wire flash_io1_do_core;
  input flash_io1_ie_core;
  wire flash_io1_ie_core;
  input flash_io1_oe_core;
  wire flash_io1_oe_core;
  inout gpio;
  wire gpio;
  input [1:0] gpio_drive_select_core;
  wire [1:0] gpio_drive_select_core;
  output gpio_in_core;
  wire gpio_in_core;
  input gpio_inen_core;
  wire gpio_inen_core;
  input gpio_out_core;
  wire gpio_out_core;
  input gpio_outen_core;
  wire gpio_outen_core;
  input gpio_pd_select;
  wire gpio_pd_select;
  input gpio_pu_select;
  wire gpio_pu_select;
  input gpio_schmitt_select;
  wire gpio_schmitt_select;
  input gpio_slew_select;
  wire gpio_slew_select;
  inout [37:0] mprj_io;
  wire [37:0] mprj_io;
  input [75:0] mprj_io_drive_sel;
  wire [75:0] mprj_io_drive_sel;
  output [37:0] mprj_io_in;
  wire [37:0] mprj_io_in;
  input [37:0] mprj_io_inen;
  wire [37:0] mprj_io_inen;
  input [37:0] mprj_io_out;
  wire [37:0] mprj_io_out;
  input [37:0] mprj_io_outen;
  wire [37:0] mprj_io_outen;
  input [37:0] mprj_io_pd_select;
  wire [37:0] mprj_io_pd_select;
  input [37:0] mprj_io_pu_select;
  wire [37:0] mprj_io_pu_select;
  input [37:0] mprj_io_schmitt_select;
  wire [37:0] mprj_io_schmitt_select;
  input [37:0] mprj_io_slew_select;
  wire [37:0] mprj_io_slew_select;
  input resetb;
  wire resetb;
  output resetb_core;
  wire resetb_core;
  inout vdd;
  wire vdd;
  inout vss;
  wire vss;
  gf180mcu_fd_io__bi_t flash_clk_pad (
    .A(flash_clk_core),
    .CS(const_zero[2]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(const_zero[2]),
    .OE(flash_clk_oe_core),
    .PAD(flash_clk),
    .PD(const_zero[2]),
    .PDRV0(const_zero[2]),
    .PDRV1(const_zero[2]),
    .PU(const_zero[2]),
    .SL(const_zero[2]),
    .VDD(vdd),
    .VSS(vss)
  );
  gf180mcu_fd_io__bi_t flash_csb_pad (
    .A(flash_csb_core),
    .CS(const_zero[3]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(const_zero[3]),
    .OE(flash_csb_oe_core),
    .PAD(flash_csb),
    .PD(const_zero[3]),
    .PDRV0(const_zero[3]),
    .PDRV1(const_zero[3]),
    .PU(const_one[0]),
    .SL(const_zero[3]),
    .VDD(vdd),
    .VSS(vss)
  );
  gf180mcu_fd_io__bi_t flash_io0_pad (
    .A(flash_io0_do_core),
    .CS(const_zero[1]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(flash_io0_ie_core),
    .OE(flash_io0_oe_core),
    .PAD(flash_io0),
    .PD(const_zero[1]),
    .PDRV0(const_zero[1]),
    .PDRV1(const_zero[1]),
    .PU(const_zero[1]),
    .SL(const_zero[1]),
    .VDD(vdd),
    .VSS(vss),
    .Y(flash_io0_di_core)
  );
  gf180mcu_fd_io__bi_t flash_io1_pad (
    .A(flash_io1_do_core),
    .CS(const_zero[0]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(flash_io1_ie_core),
    .OE(flash_io1_oe_core),
    .PAD(flash_io1),
    .PD(const_zero[0]),
    .PDRV0(const_zero[0]),
    .PDRV1(const_zero[0]),
    .PU(const_zero[0]),
    .SL(const_zero[0]),
    .VDD(vdd),
    .VSS(vss),
    .Y(flash_io1_di_core)
  );
  gf180mcu_fd_io__bi_t \mprj_pads[0]  (
    .A(mprj_io_out[0]),
    .CS(mprj_io_schmitt_select[0]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[0]),
    .OE(mprj_io_outen[0]),
    .PAD(mprj_io[0]),
    .PD(mprj_io_pd_select[0]),
    .PDRV0(mprj_io_drive_sel[0]),
    .PDRV1(mprj_io_drive_sel[1]),
    .PU(mprj_io_pu_select[0]),
    .SL(mprj_io_slew_select[0]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[0])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[10]  (
    .A(mprj_io_out[10]),
    .CS(mprj_io_schmitt_select[10]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[10]),
    .OE(mprj_io_outen[10]),
    .PAD(mprj_io[10]),
    .PD(mprj_io_pd_select[10]),
    .PDRV0(mprj_io_drive_sel[20]),
    .PDRV1(mprj_io_drive_sel[21]),
    .PU(mprj_io_pu_select[10]),
    .SL(mprj_io_slew_select[10]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[10])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[11]  (
    .A(mprj_io_out[11]),
    .CS(mprj_io_schmitt_select[11]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[11]),
    .OE(mprj_io_outen[11]),
    .PAD(mprj_io[11]),
    .PD(mprj_io_pd_select[11]),
    .PDRV0(mprj_io_drive_sel[22]),
    .PDRV1(mprj_io_drive_sel[23]),
    .PU(mprj_io_pu_select[11]),
    .SL(mprj_io_slew_select[11]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[11])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[12]  (
    .A(mprj_io_out[12]),
    .CS(mprj_io_schmitt_select[12]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[12]),
    .OE(mprj_io_outen[12]),
    .PAD(mprj_io[12]),
    .PD(mprj_io_pd_select[12]),
    .PDRV0(mprj_io_drive_sel[24]),
    .PDRV1(mprj_io_drive_sel[25]),
    .PU(mprj_io_pu_select[12]),
    .SL(mprj_io_slew_select[12]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[12])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[13]  (
    .A(mprj_io_out[13]),
    .CS(mprj_io_schmitt_select[13]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[13]),
    .OE(mprj_io_outen[13]),
    .PAD(mprj_io[13]),
    .PD(mprj_io_pd_select[13]),
    .PDRV0(mprj_io_drive_sel[26]),
    .PDRV1(mprj_io_drive_sel[27]),
    .PU(mprj_io_pu_select[13]),
    .SL(mprj_io_slew_select[13]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[13])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[14]  (
    .A(mprj_io_out[14]),
    .CS(mprj_io_schmitt_select[14]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[14]),
    .OE(mprj_io_outen[14]),
    .PAD(mprj_io[14]),
    .PD(mprj_io_pd_select[14]),
    .PDRV0(mprj_io_drive_sel[28]),
    .PDRV1(mprj_io_drive_sel[29]),
    .PU(mprj_io_pu_select[14]),
    .SL(mprj_io_slew_select[14]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[14])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[15]  (
    .A(mprj_io_out[15]),
    .CS(mprj_io_schmitt_select[15]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[15]),
    .OE(mprj_io_outen[15]),
    .PAD(mprj_io[15]),
    .PD(mprj_io_pd_select[15]),
    .PDRV0(mprj_io_drive_sel[30]),
    .PDRV1(mprj_io_drive_sel[31]),
    .PU(mprj_io_pu_select[15]),
    .SL(mprj_io_slew_select[15]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[15])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[16]  (
    .A(mprj_io_out[16]),
    .CS(mprj_io_schmitt_select[16]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[16]),
    .OE(mprj_io_outen[16]),
    .PAD(mprj_io[16]),
    .PD(mprj_io_pd_select[16]),
    .PDRV0(mprj_io_drive_sel[32]),
    .PDRV1(mprj_io_drive_sel[33]),
    .PU(mprj_io_pu_select[16]),
    .SL(mprj_io_slew_select[16]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[16])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[17]  (
    .A(mprj_io_out[17]),
    .CS(mprj_io_schmitt_select[17]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[17]),
    .OE(mprj_io_outen[17]),
    .PAD(mprj_io[17]),
    .PD(mprj_io_pd_select[17]),
    .PDRV0(mprj_io_drive_sel[34]),
    .PDRV1(mprj_io_drive_sel[35]),
    .PU(mprj_io_pu_select[17]),
    .SL(mprj_io_slew_select[17]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[17])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[18]  (
    .A(mprj_io_out[18]),
    .CS(mprj_io_schmitt_select[18]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[18]),
    .OE(mprj_io_outen[18]),
    .PAD(mprj_io[18]),
    .PD(mprj_io_pd_select[18]),
    .PDRV0(mprj_io_drive_sel[36]),
    .PDRV1(mprj_io_drive_sel[37]),
    .PU(mprj_io_pu_select[18]),
    .SL(mprj_io_slew_select[18]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[18])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[19]  (
    .A(mprj_io_out[19]),
    .CS(mprj_io_schmitt_select[19]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[19]),
    .OE(mprj_io_outen[19]),
    .PAD(mprj_io[19]),
    .PD(mprj_io_pd_select[19]),
    .PDRV0(mprj_io_drive_sel[38]),
    .PDRV1(mprj_io_drive_sel[39]),
    .PU(mprj_io_pu_select[19]),
    .SL(mprj_io_slew_select[19]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[19])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[1]  (
    .A(mprj_io_out[1]),
    .CS(mprj_io_schmitt_select[1]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[1]),
    .OE(mprj_io_outen[1]),
    .PAD(mprj_io[1]),
    .PD(mprj_io_pd_select[1]),
    .PDRV0(mprj_io_drive_sel[2]),
    .PDRV1(mprj_io_drive_sel[3]),
    .PU(mprj_io_pu_select[1]),
    .SL(mprj_io_slew_select[1]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[1])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[20]  (
    .A(mprj_io_out[20]),
    .CS(mprj_io_schmitt_select[20]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[20]),
    .OE(mprj_io_outen[20]),
    .PAD(mprj_io[20]),
    .PD(mprj_io_pd_select[20]),
    .PDRV0(mprj_io_drive_sel[40]),
    .PDRV1(mprj_io_drive_sel[41]),
    .PU(mprj_io_pu_select[20]),
    .SL(mprj_io_slew_select[20]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[20])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[21]  (
    .A(mprj_io_out[21]),
    .CS(mprj_io_schmitt_select[21]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[21]),
    .OE(mprj_io_outen[21]),
    .PAD(mprj_io[21]),
    .PD(mprj_io_pd_select[21]),
    .PDRV0(mprj_io_drive_sel[42]),
    .PDRV1(mprj_io_drive_sel[43]),
    .PU(mprj_io_pu_select[21]),
    .SL(mprj_io_slew_select[21]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[21])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[22]  (
    .A(mprj_io_out[22]),
    .CS(mprj_io_schmitt_select[22]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[22]),
    .OE(mprj_io_outen[22]),
    .PAD(mprj_io[22]),
    .PD(mprj_io_pd_select[22]),
    .PDRV0(mprj_io_drive_sel[44]),
    .PDRV1(mprj_io_drive_sel[45]),
    .PU(mprj_io_pu_select[22]),
    .SL(mprj_io_slew_select[22]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[22])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[23]  (
    .A(mprj_io_out[23]),
    .CS(mprj_io_schmitt_select[23]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[23]),
    .OE(mprj_io_outen[23]),
    .PAD(mprj_io[23]),
    .PD(mprj_io_pd_select[23]),
    .PDRV0(mprj_io_drive_sel[46]),
    .PDRV1(mprj_io_drive_sel[47]),
    .PU(mprj_io_pu_select[23]),
    .SL(mprj_io_slew_select[23]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[23])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[24]  (
    .A(mprj_io_out[24]),
    .CS(mprj_io_schmitt_select[24]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[24]),
    .OE(mprj_io_outen[24]),
    .PAD(mprj_io[24]),
    .PD(mprj_io_pd_select[24]),
    .PDRV0(mprj_io_drive_sel[48]),
    .PDRV1(mprj_io_drive_sel[49]),
    .PU(mprj_io_pu_select[24]),
    .SL(mprj_io_slew_select[24]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[24])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[25]  (
    .A(mprj_io_out[25]),
    .CS(mprj_io_schmitt_select[25]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[25]),
    .OE(mprj_io_outen[25]),
    .PAD(mprj_io[25]),
    .PD(mprj_io_pd_select[25]),
    .PDRV0(mprj_io_drive_sel[50]),
    .PDRV1(mprj_io_drive_sel[51]),
    .PU(mprj_io_pu_select[25]),
    .SL(mprj_io_slew_select[25]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[25])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[26]  (
    .A(mprj_io_out[26]),
    .CS(mprj_io_schmitt_select[26]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[26]),
    .OE(mprj_io_outen[26]),
    .PAD(mprj_io[26]),
    .PD(mprj_io_pd_select[26]),
    .PDRV0(mprj_io_drive_sel[52]),
    .PDRV1(mprj_io_drive_sel[53]),
    .PU(mprj_io_pu_select[26]),
    .SL(mprj_io_slew_select[26]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[26])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[27]  (
    .A(mprj_io_out[27]),
    .CS(mprj_io_schmitt_select[27]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[27]),
    .OE(mprj_io_outen[27]),
    .PAD(mprj_io[27]),
    .PD(mprj_io_pd_select[27]),
    .PDRV0(mprj_io_drive_sel[54]),
    .PDRV1(mprj_io_drive_sel[55]),
    .PU(mprj_io_pu_select[27]),
    .SL(mprj_io_slew_select[27]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[27])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[28]  (
    .A(mprj_io_out[28]),
    .CS(mprj_io_schmitt_select[28]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[28]),
    .OE(mprj_io_outen[28]),
    .PAD(mprj_io[28]),
    .PD(mprj_io_pd_select[28]),
    .PDRV0(mprj_io_drive_sel[56]),
    .PDRV1(mprj_io_drive_sel[57]),
    .PU(mprj_io_pu_select[28]),
    .SL(mprj_io_slew_select[28]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[28])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[29]  (
    .A(mprj_io_out[29]),
    .CS(mprj_io_schmitt_select[29]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[29]),
    .OE(mprj_io_outen[29]),
    .PAD(mprj_io[29]),
    .PD(mprj_io_pd_select[29]),
    .PDRV0(mprj_io_drive_sel[58]),
    .PDRV1(mprj_io_drive_sel[59]),
    .PU(mprj_io_pu_select[29]),
    .SL(mprj_io_slew_select[29]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[29])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[2]  (
    .A(mprj_io_out[2]),
    .CS(mprj_io_schmitt_select[2]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[2]),
    .OE(mprj_io_outen[2]),
    .PAD(mprj_io[2]),
    .PD(mprj_io_pd_select[2]),
    .PDRV0(mprj_io_drive_sel[4]),
    .PDRV1(mprj_io_drive_sel[5]),
    .PU(mprj_io_pu_select[2]),
    .SL(mprj_io_slew_select[2]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[2])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[30]  (
    .A(mprj_io_out[30]),
    .CS(mprj_io_schmitt_select[30]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[30]),
    .OE(mprj_io_outen[30]),
    .PAD(mprj_io[30]),
    .PD(mprj_io_pd_select[30]),
    .PDRV0(mprj_io_drive_sel[60]),
    .PDRV1(mprj_io_drive_sel[61]),
    .PU(mprj_io_pu_select[30]),
    .SL(mprj_io_slew_select[30]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[30])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[31]  (
    .A(mprj_io_out[31]),
    .CS(mprj_io_schmitt_select[31]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[31]),
    .OE(mprj_io_outen[31]),
    .PAD(mprj_io[31]),
    .PD(mprj_io_pd_select[31]),
    .PDRV0(mprj_io_drive_sel[62]),
    .PDRV1(mprj_io_drive_sel[63]),
    .PU(mprj_io_pu_select[31]),
    .SL(mprj_io_slew_select[31]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[31])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[32]  (
    .A(mprj_io_out[32]),
    .CS(mprj_io_schmitt_select[32]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[32]),
    .OE(mprj_io_outen[32]),
    .PAD(mprj_io[32]),
    .PD(mprj_io_pd_select[32]),
    .PDRV0(mprj_io_drive_sel[64]),
    .PDRV1(mprj_io_drive_sel[65]),
    .PU(mprj_io_pu_select[32]),
    .SL(mprj_io_slew_select[32]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[32])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[33]  (
    .A(mprj_io_out[33]),
    .CS(mprj_io_schmitt_select[33]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[33]),
    .OE(mprj_io_outen[33]),
    .PAD(mprj_io[33]),
    .PD(mprj_io_pd_select[33]),
    .PDRV0(mprj_io_drive_sel[66]),
    .PDRV1(mprj_io_drive_sel[67]),
    .PU(mprj_io_pu_select[33]),
    .SL(mprj_io_slew_select[33]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[33])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[34]  (
    .A(mprj_io_out[34]),
    .CS(mprj_io_schmitt_select[34]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[34]),
    .OE(mprj_io_outen[34]),
    .PAD(mprj_io[34]),
    .PD(mprj_io_pd_select[34]),
    .PDRV0(mprj_io_drive_sel[68]),
    .PDRV1(mprj_io_drive_sel[69]),
    .PU(mprj_io_pu_select[34]),
    .SL(mprj_io_slew_select[34]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[34])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[35]  (
    .A(mprj_io_out[35]),
    .CS(mprj_io_schmitt_select[35]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[35]),
    .OE(mprj_io_outen[35]),
    .PAD(mprj_io[35]),
    .PD(mprj_io_pd_select[35]),
    .PDRV0(mprj_io_drive_sel[70]),
    .PDRV1(mprj_io_drive_sel[71]),
    .PU(mprj_io_pu_select[35]),
    .SL(mprj_io_slew_select[35]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[35])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[36]  (
    .A(mprj_io_out[36]),
    .CS(mprj_io_schmitt_select[36]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[36]),
    .OE(mprj_io_outen[36]),
    .PAD(mprj_io[36]),
    .PD(mprj_io_pd_select[36]),
    .PDRV0(mprj_io_drive_sel[72]),
    .PDRV1(mprj_io_drive_sel[73]),
    .PU(mprj_io_pu_select[36]),
    .SL(mprj_io_slew_select[36]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[36])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[37]  (
    .A(mprj_io_out[37]),
    .CS(mprj_io_schmitt_select[37]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[37]),
    .OE(mprj_io_outen[37]),
    .PAD(mprj_io[37]),
    .PD(mprj_io_pd_select[37]),
    .PDRV0(mprj_io_drive_sel[74]),
    .PDRV1(mprj_io_drive_sel[75]),
    .PU(mprj_io_pu_select[37]),
    .SL(mprj_io_slew_select[37]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[37])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[3]  (
    .A(mprj_io_out[3]),
    .CS(mprj_io_schmitt_select[3]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[3]),
    .OE(mprj_io_outen[3]),
    .PAD(mprj_io[3]),
    .PD(mprj_io_pd_select[3]),
    .PDRV0(mprj_io_drive_sel[6]),
    .PDRV1(mprj_io_drive_sel[7]),
    .PU(mprj_io_pu_select[3]),
    .SL(mprj_io_slew_select[3]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[3])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[4]  (
    .A(mprj_io_out[4]),
    .CS(mprj_io_schmitt_select[4]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[4]),
    .OE(mprj_io_outen[4]),
    .PAD(mprj_io[4]),
    .PD(mprj_io_pd_select[4]),
    .PDRV0(mprj_io_drive_sel[8]),
    .PDRV1(mprj_io_drive_sel[9]),
    .PU(mprj_io_pu_select[4]),
    .SL(mprj_io_slew_select[4]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[4])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[5]  (
    .A(mprj_io_out[5]),
    .CS(mprj_io_schmitt_select[5]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[5]),
    .OE(mprj_io_outen[5]),
    .PAD(mprj_io[5]),
    .PD(mprj_io_pd_select[5]),
    .PDRV0(mprj_io_drive_sel[10]),
    .PDRV1(mprj_io_drive_sel[11]),
    .PU(mprj_io_pu_select[5]),
    .SL(mprj_io_slew_select[5]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[5])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[6]  (
    .A(mprj_io_out[6]),
    .CS(mprj_io_schmitt_select[6]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[6]),
    .OE(mprj_io_outen[6]),
    .PAD(mprj_io[6]),
    .PD(mprj_io_pd_select[6]),
    .PDRV0(mprj_io_drive_sel[12]),
    .PDRV1(mprj_io_drive_sel[13]),
    .PU(mprj_io_pu_select[6]),
    .SL(mprj_io_slew_select[6]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[6])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[7]  (
    .A(mprj_io_out[7]),
    .CS(mprj_io_schmitt_select[7]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[7]),
    .OE(mprj_io_outen[7]),
    .PAD(mprj_io[7]),
    .PD(mprj_io_pd_select[7]),
    .PDRV0(mprj_io_drive_sel[14]),
    .PDRV1(mprj_io_drive_sel[15]),
    .PU(mprj_io_pu_select[7]),
    .SL(mprj_io_slew_select[7]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[7])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[8]  (
    .A(mprj_io_out[8]),
    .CS(mprj_io_schmitt_select[8]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[8]),
    .OE(mprj_io_outen[8]),
    .PAD(mprj_io[8]),
    .PD(mprj_io_pd_select[8]),
    .PDRV0(mprj_io_drive_sel[16]),
    .PDRV1(mprj_io_drive_sel[17]),
    .PU(mprj_io_pu_select[8]),
    .SL(mprj_io_slew_select[8]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[8])
  );
  gf180mcu_fd_io__bi_t \mprj_pads[9]  (
    .A(mprj_io_out[9]),
    .CS(mprj_io_schmitt_select[9]),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(mprj_io_inen[9]),
    .OE(mprj_io_outen[9]),
    .PAD(mprj_io[9]),
    .PD(mprj_io_pd_select[9]),
    .PDRV0(mprj_io_drive_sel[18]),
    .PDRV1(mprj_io_drive_sel[19]),
    .PU(mprj_io_pu_select[9]),
    .SL(mprj_io_slew_select[9]),
    .VDD(vdd),
    .VSS(vss),
    .Y(mprj_io_in[9])
  );
  gf180mcu_fd_io__in_c mgmt_clock_input_pad (
    .DVDD(vdd),
    .DVSS(vss),
    .PAD(clock),
    .PD(const_zero[4]),
    .PU(const_zero[4]),
    .VDD(vdd),
    .VSS(vss),
    .Y(clock_core)
  );
  gf180mcu_fd_io__cor \mgmt_corner[0]  (
    .DVDD(vdd),
    .DVSS(vss),
    .VDD(vdd),
    .VSS(vss)
  );
  gf180mcu_fd_io__cor \mgmt_corner[1]  (
    .DVDD(vdd),
    .DVSS(vss),
    .VDD(vdd),
    .VSS(vss)
  );
  gf180mcu_fd_io__bi_t mgmt_gpio_pad (
    .A(gpio_out_core),
    .CS(gpio_schmitt_select),
    .DVDD(vdd),
    .DVSS(vss),
    .IE(gpio_inen_core),
    .OE(gpio_outen_core),
    .PAD(gpio),
    .PD(gpio_pd_select),
    .PDRV0(gpio_drive_select_core[0]),
    .PDRV1(gpio_drive_select_core[1]),
    .PU(gpio_pu_select),
    .SL(gpio_slew_select),
    .VDD(vdd),
    .VSS(vss),
    .Y(gpio_in_core)
  );
  gf180mcu_fd_io__dvdd mgmt_vccd_pad (
    .DVDD(vdd),
    .DVSS(vss),
    .VSS(vss)
  );
  gf180mcu_fd_io__dvdd mgmt_vdda_pad (
    .DVDD(vdd),
    .DVSS(vss),
    .VSS(vss)
  );
  gf180mcu_fd_io__dvdd mgmt_vddio_pad_0 (
    .DVDD(vdd),
    .DVSS(vss),
    .VSS(vss)
  );
  gf180mcu_fd_io__dvdd mgmt_vddio_pad_1 (
    .DVDD(vdd),
    .DVSS(vss),
    .VSS(vss)
  );
  gf180mcu_fd_io__dvss mgmt_vssa_pad (
    .DVDD(vdd),
    .DVSS(vss),
    .VDD(vdd)
  );
  gf180mcu_fd_io__dvss mgmt_vssd_pad (
    .DVDD(vdd),
    .DVSS(vss),
    .VDD(vdd)
  );
  gf180mcu_fd_io__dvss mgmt_vssio_pad_0 (
    .DVDD(vdd),
    .DVSS(vss),
    .VDD(vdd)
  );
  gf180mcu_fd_io__dvss mgmt_vssio_pad_1 (
    .DVDD(vdd),
    .DVSS(vss),
    .VDD(vdd)
  );
  gf180mcu_fd_io__in_s resetb_pad (
    .DVDD(vdd),
    .DVSS(vss),
    .PAD(resetb),
    .PD(const_zero[5]),
    .PU(const_one[1]),
    .VDD(vdd),
    .VSS(vss),
    .Y(resetb_core)
  );
  gf180mcu_fd_io__cor user1_corner (
    .DVDD(vdd),
    .DVSS(vss),
    .VDD(vdd),
    .VSS(vss)
  );
  gf180mcu_fd_io__dvdd user1_vccd_pad (
    .DVDD(vdd),
    .DVSS(vss),
    .VSS(vss)
  );
  gf180mcu_fd_io__dvdd user1_vdda_pad_0 (
    .DVDD(vdd),
    .DVSS(vss),
    .VSS(vss)
  );
  gf180mcu_fd_io__dvdd user1_vdda_pad_1 (
    .DVDD(vdd),
    .DVSS(vss),
    .VSS(vss)
  );
  gf180mcu_fd_io__dvss user1_vssa_pad_0 (
    .DVDD(vdd),
    .DVSS(vss),
    .VDD(vdd)
  );
  gf180mcu_fd_io__dvss user1_vssa_pad_1 (
    .DVDD(vdd),
    .DVSS(vss),
    .VDD(vdd)
  );
  gf180mcu_fd_io__dvss user1_vssd_pad (
    .DVDD(vdd),
    .DVSS(vss),
    .VDD(vdd)
  );
  gf180mcu_fd_io__cor user2_corner (
    .DVDD(vdd),
    .DVSS(vss),
    .VDD(vdd),
    .VSS(vss)
  );
  gf180mcu_fd_io__dvdd user2_vccd_pad (
    .DVDD(vdd),
    .DVSS(vss),
    .VSS(vss)
  );
  gf180mcu_fd_io__dvdd user2_vdda_pad (
    .DVDD(vdd),
    .DVSS(vss),
    .VSS(vss)
  );
  gf180mcu_fd_io__dvss user2_vssa_pad (
    .DVDD(vdd),
    .DVSS(vss),
    .VDD(vdd)
  );
  gf180mcu_fd_io__dvss user2_vssd_pad (
    .DVDD(vdd),
    .DVSS(vss),
    .VDD(vdd)
  );
endmodule
