/* Generated by Yosys 0.22 (git sha1 f109fa3d4c5, gcc 8.3.1 -fPIC -Os) */

module gpio_defaults_block(VDD, VSS, gpio_defaults);
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
  output [9:0] gpio_defaults;
  wire [9:0] gpio_defaults;
  wire \gpio_defaults_high[0] ;
  wire \gpio_defaults_high[1] ;
  wire \gpio_defaults_high[2] ;
  wire \gpio_defaults_high[3] ;
  wire \gpio_defaults_high[4] ;
  wire \gpio_defaults_high[5] ;
  wire \gpio_defaults_high[6] ;
  wire \gpio_defaults_high[7] ;
  wire \gpio_defaults_high[8] ;
  wire \gpio_defaults_high[9] ;
  wire \gpio_defaults_low[0] ;
  wire \gpio_defaults_low[1] ;
  wire \gpio_defaults_low[2] ;
  wire \gpio_defaults_low[3] ;
  wire \gpio_defaults_low[4] ;
  wire \gpio_defaults_low[5] ;
  wire \gpio_defaults_low[6] ;
  wire \gpio_defaults_low[7] ;
  wire \gpio_defaults_low[8] ;
  wire \gpio_defaults_low[9] ;
  gf180mcu_fd_sc_mcu7t5v0__tieh \gpio_default_value_one[0]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\gpio_defaults_high[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \gpio_default_value_one[1]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\gpio_defaults_high[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \gpio_default_value_one[2]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\gpio_defaults_high[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \gpio_default_value_one[3]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\gpio_defaults_high[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \gpio_default_value_one[4]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\gpio_defaults_high[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \gpio_default_value_one[5]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\gpio_defaults_high[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \gpio_default_value_one[6]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\gpio_defaults_high[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \gpio_default_value_one[7]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\gpio_defaults_high[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \gpio_default_value_one[8]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\gpio_defaults_high[8] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \gpio_default_value_one[9]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\gpio_defaults_high[9] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \gpio_default_value_zero[0]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\gpio_defaults_low[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \gpio_default_value_zero[1]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\gpio_defaults_low[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \gpio_default_value_zero[2]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\gpio_defaults_low[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \gpio_default_value_zero[3]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\gpio_defaults_low[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \gpio_default_value_zero[4]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\gpio_defaults_low[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \gpio_default_value_zero[5]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\gpio_defaults_low[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \gpio_default_value_zero[6]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\gpio_defaults_low[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \gpio_default_value_zero[7]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\gpio_defaults_low[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \gpio_default_value_zero[8]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\gpio_defaults_low[8] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \gpio_default_value_zero[9]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\gpio_defaults_low[9] )
  );
  assign gpio_defaults = { \gpio_defaults_low[9] , \gpio_defaults_low[8] , \gpio_defaults_low[7] , \gpio_defaults_low[6] , \gpio_defaults_low[5] , \gpio_defaults_low[4] , \gpio_defaults_low[3] , \gpio_defaults_high[2] , \gpio_defaults_high[1] , \gpio_defaults_high[0]  };
endmodule
