/* Generated by Yosys 0.22 (git sha1 f109fa3d4c5, gcc 8.3.1 -fPIC -Os) */

module user_id_programming(VDD, VSS, mask_rev);
  inout VDD;
  wire VDD;
  inout VSS;
  wire VSS;
  output [31:0] mask_rev;
  wire [31:0] mask_rev;
  wire \user_proj_id_high[0] ;
  wire \user_proj_id_high[10] ;
  wire \user_proj_id_high[11] ;
  wire \user_proj_id_high[12] ;
  wire \user_proj_id_high[13] ;
  wire \user_proj_id_high[14] ;
  wire \user_proj_id_high[15] ;
  wire \user_proj_id_high[16] ;
  wire \user_proj_id_high[17] ;
  wire \user_proj_id_high[18] ;
  wire \user_proj_id_high[19] ;
  wire \user_proj_id_high[1] ;
  wire \user_proj_id_high[20] ;
  wire \user_proj_id_high[21] ;
  wire \user_proj_id_high[22] ;
  wire \user_proj_id_high[23] ;
  wire \user_proj_id_high[24] ;
  wire \user_proj_id_high[25] ;
  wire \user_proj_id_high[26] ;
  wire \user_proj_id_high[27] ;
  wire \user_proj_id_high[28] ;
  wire \user_proj_id_high[29] ;
  wire \user_proj_id_high[2] ;
  wire \user_proj_id_high[30] ;
  wire \user_proj_id_high[31] ;
  wire \user_proj_id_high[3] ;
  wire \user_proj_id_high[4] ;
  wire \user_proj_id_high[5] ;
  wire \user_proj_id_high[6] ;
  wire \user_proj_id_high[7] ;
  wire \user_proj_id_high[8] ;
  wire \user_proj_id_high[9] ;
  wire \user_proj_id_low[0] ;
  wire \user_proj_id_low[10] ;
  wire \user_proj_id_low[11] ;
  wire \user_proj_id_low[12] ;
  wire \user_proj_id_low[13] ;
  wire \user_proj_id_low[14] ;
  wire \user_proj_id_low[15] ;
  wire \user_proj_id_low[16] ;
  wire \user_proj_id_low[17] ;
  wire \user_proj_id_low[18] ;
  wire \user_proj_id_low[19] ;
  wire \user_proj_id_low[1] ;
  wire \user_proj_id_low[20] ;
  wire \user_proj_id_low[21] ;
  wire \user_proj_id_low[22] ;
  wire \user_proj_id_low[23] ;
  wire \user_proj_id_low[24] ;
  wire \user_proj_id_low[25] ;
  wire \user_proj_id_low[26] ;
  wire \user_proj_id_low[27] ;
  wire \user_proj_id_low[28] ;
  wire \user_proj_id_low[29] ;
  wire \user_proj_id_low[2] ;
  wire \user_proj_id_low[30] ;
  wire \user_proj_id_low[31] ;
  wire \user_proj_id_low[3] ;
  wire \user_proj_id_low[4] ;
  wire \user_proj_id_low[5] ;
  wire \user_proj_id_low[6] ;
  wire \user_proj_id_low[7] ;
  wire \user_proj_id_low[8] ;
  wire \user_proj_id_low[9] ;
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[0]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[10]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[10] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[11]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[11] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[12]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[12] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[13]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[13] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[14]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[14] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[15]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[15] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[16]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[16] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[17]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[17] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[18]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[18] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[19]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[19] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[1]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[20]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[20] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[21]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[21] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[22]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[22] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[23]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[23] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[24]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[24] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[25]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[25] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[26]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[26] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[27]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[27] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[28]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[28] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[29]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[29] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[2]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[30]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[30] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[31]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[31] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[3]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[4]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[5]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[6]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[7]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[8]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[8] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tieh \mask_rev_value_one[9]  (
    .VDD(VDD),
    .VSS(VSS),
    .Z(\user_proj_id_high[9] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[0]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[0] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[10]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[10] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[11]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[11] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[12]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[12] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[13]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[13] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[14]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[14] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[15]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[15] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[16]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[16] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[17]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[17] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[18]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[18] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[19]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[19] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[1]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[1] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[20]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[20] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[21]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[21] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[22]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[22] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[23]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[23] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[24]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[24] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[25]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[25] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[26]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[26] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[27]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[27] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[28]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[28] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[29]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[29] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[2]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[2] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[30]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[30] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[31]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[31] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[3]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[3] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[4]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[4] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[5]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[5] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[6]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[6] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[7]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[7] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[8]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[8] )
  );
  gf180mcu_fd_sc_mcu7t5v0__tiel \mask_rev_value_zero[9]  (
    .VDD(VDD),
    .VSS(VSS),
    .ZN(\user_proj_id_low[9] )
  );
  assign mask_rev = { \user_proj_id_low[31] , \user_proj_id_low[30] , \user_proj_id_low[29] , \user_proj_id_low[28] , \user_proj_id_low[27] , \user_proj_id_low[26] , \user_proj_id_low[25] , \user_proj_id_low[24] , \user_proj_id_low[23] , \user_proj_id_low[22] , \user_proj_id_low[21] , \user_proj_id_low[20] , \user_proj_id_low[19] , \user_proj_id_low[18] , \user_proj_id_low[17] , \user_proj_id_low[16] , \user_proj_id_low[15] , \user_proj_id_low[14] , \user_proj_id_low[13] , \user_proj_id_low[12] , \user_proj_id_low[11] , \user_proj_id_low[10] , \user_proj_id_low[9] , \user_proj_id_low[8] , \user_proj_id_low[7] , \user_proj_id_low[6] , \user_proj_id_low[5] , \user_proj_id_low[4] , \user_proj_id_low[3] , \user_proj_id_low[2] , \user_proj_id_low[1] , \user_proj_id_low[0]  };
endmodule
