# Run configs
set ::env(PDK_ROOT) {/home/passant/OpenLane/pdks}
set ::env(BASE_SDC_FILE) {/openlane/scripts/base.sdc}
set ::env(BOTTOM_MARGIN_MULT) {4}
set ::env(CARRY_SELECT_ADDER_MAP) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/csa_map.v}
set ::env(CELLS_LEF) {/home/passant/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/lef/gf180mcu_fd_sc_mcu7t5v0.lef}
set ::env(CELL_PAD_EXCLUDE) {gf180mcu_fd_sc_mcu7t5v0__filltie_* gf180mcu_fd_sc_mcu7t5v0__filldecap_* gf180mcu_fd_sc_mcu7t5v0__fill_* gf180mcu_fd_sc_mcu7t5v0__endcap_*}
set ::env(CHECK_ASSIGN_STATEMENTS) {0}
set ::env(CHECK_UNMAPPED_CELLS) {1}
set ::env(CLOCK_BUFFER_FANOUT) {16}
set ::env(CLOCK_PERIOD) {10.0}
set ::env(CLOCK_TREE_SYNTH) {1}
set ::env(CLOCK_WIRE_RC_LAYER) {Metal4}
set ::env(CONFIGS) {general.tcl checkers.tcl synthesis.tcl floorplan.tcl cts.tcl placement.tcl routing.tcl extraction.tcl}
set ::env(CTS_CLK_BUFFER_LIST) {gf180mcu_fd_sc_mcu7t5v0__clkbuf_2 gf180mcu_fd_sc_mcu7t5v0__clkbuf_4 gf180mcu_fd_sc_mcu7t5v0__clkbuf_8}
set ::env(CTS_CLK_MAX_WIRE_LENGTH) {0}
set ::env(CTS_DISABLE_POST_PROCESSING) {0}
set ::env(CTS_DISTANCE_BETWEEN_BUFFERS) {0}
set ::env(CTS_MAX_CAP) {0.5}
set ::env(CTS_REPORT_TIMING) {1}
set ::env(CTS_ROOT_BUFFER) {gf180mcu_fd_sc_mcu7t5v0__clkbuf_16}
set ::env(CTS_SINK_CLUSTERING_MAX_DIAMETER) {50}
set ::env(CTS_SINK_CLUSTERING_SIZE) {25}
set ::env(CTS_TARGET_SKEW) {200}
set ::env(CTS_TOLERANCE) {100}
set ::env(DATA_WIRE_RC_LAYER) {Metal2}
set ::env(DECAP_CELL) {gf180mcu_fd_sc_mcu7t5v0__fillcap_*}
set ::env(DEFAULT_MAX_TRAN) {3}
set ::env(DEF_UNITS_PER_MICRON) {2000}
set ::env(DESIGN_CONFIG) {/home/passant/caravel-gf180mcu/openlane/chip_io/config.tcl}
set ::env(DESIGN_IS_CORE) {1}
set ::env(DESIGN_NAME) {chip_io}
set ::env(DETAILED_ROUTER) {tritonroute}
set ::env(DIODE_CELL) {gf180mcu_fd_sc_mcu7t5v0__antenna}
set ::env(DIODE_CELL_PIN) {I}
set ::env(DIODE_INSERTION_STRATEGY) {4}
set ::env(DIODE_PADDING) {2}
set ::env(DPL_CELL_PADDING) {2}
set ::env(DRC_EXCLUDE_CELL_LIST) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/drc_exclude.cells}
set ::env(DRC_EXCLUDE_CELL_LIST_OPT) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/drc_exclude.cells}
set ::env(DRT_MIN_LAYER) {Metal1}
set ::env(DRT_OPT_ITERS) {64}
set ::env(ECO_ENABLE) {0}
set ::env(ECO_FINISH) {0}
set ::env(ECO_ITER) {0}
set ::env(ECO_SKIP_PIN) {1}
set ::env(EXTRA_LIBS) {/home/passant/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_io/liberty/gf180mcu_fd_io__tt_025C_3v30.lib}
set ::env(FILL_CELL) {gf180mcu_fd_sc_mcu7t5v0__fill_*}
set ::env(FP_ASPECT_RATIO) {1}
set ::env(FP_CORE_UTIL) {50}
set ::env(FP_ENDCAP_CELL) {gf180mcu_fd_sc_mcu7t5v0__endcap}
set ::env(FP_IO_HEXTEND) {0}
set ::env(FP_IO_HLAYER) {Metal3}
set ::env(FP_IO_HLENGTH) {4}
set ::env(FP_IO_HTHICKNESS_MULT) {2}
set ::env(FP_IO_MIN_DISTANCE) {3}
set ::env(FP_IO_MODE) {1}
set ::env(FP_IO_UNMATCHED_ERROR) {1}
set ::env(FP_IO_VEXTEND) {0}
set ::env(FP_IO_VLAYER) {Metal2}
set ::env(FP_IO_VLENGTH) {4}
set ::env(FP_IO_VTHICKNESS_MULT) {2}
set ::env(FP_PDN_AUTO_ADJUST) {1}
set ::env(FP_PDN_CHECK_NODES) {1}
set ::env(FP_PDN_CORE_RING) {0}
set ::env(FP_PDN_CORE_RING_HOFFSET) {6}
set ::env(FP_PDN_CORE_RING_HSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_HWIDTH) {1.6}
set ::env(FP_PDN_CORE_RING_VOFFSET) {6}
set ::env(FP_PDN_CORE_RING_VSPACING) {1.7}
set ::env(FP_PDN_CORE_RING_VWIDTH) {1.6}
set ::env(FP_PDN_ENABLE_GLOBAL_CONNECTIONS) {1}
set ::env(FP_PDN_ENABLE_MACROS_GRID) {1}
set ::env(FP_PDN_ENABLE_RAILS) {1}
set ::env(FP_PDN_HOFFSET) {16.65}
set ::env(FP_PDN_HORIZONTAL_HALO) {10}
set ::env(FP_PDN_HPITCH) {153.18}
set ::env(FP_PDN_HSPACING) {1.7}
set ::env(FP_PDN_HWIDTH) {1.6}
set ::env(FP_PDN_IRDROP) {1}
set ::env(FP_PDN_LOWER_LAYER) {Metal4}
set ::env(FP_PDN_RAILS_LAYER) {Metal1}
set ::env(FP_PDN_RAIL_OFFSET) {0}
set ::env(FP_PDN_RAIL_WIDTH) {0.6}
set ::env(FP_PDN_SKIPTRIM) {0}
set ::env(FP_PDN_UPPER_LAYER) {Metal5}
set ::env(FP_PDN_VERTICAL_HALO) {10}
set ::env(FP_PDN_VOFFSET) {16.32}
set ::env(FP_PDN_VPITCH) {153.6}
set ::env(FP_PDN_VSPACING) {1.7}
set ::env(FP_PDN_VWIDTH) {1.6}
set ::env(FP_SIZING) {relative}
set ::env(FP_TAPCELL_DIST) {20}
set ::env(FP_TAP_HORIZONTAL_HALO) {10}
set ::env(FP_TAP_VERTICAL_HALO) {10}
set ::env(FP_WELLTAP_CELL) {gf180mcu_fd_sc_mcu7t5v0__filltie}
set ::env(FULL_ADDER_MAP) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/fa_map.v}
set ::env(GDS_FILES) {/home/passant/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/gds/gf180mcu_fd_sc_mcu7t5v0.gds}
set ::env(GENERATE_FINAL_SUMMARY_REPORT) {1}
set ::env(GLB_CFG_FILE) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/config.tcl}
set ::env(GLB_OPTIMIZE_MIRRORING) {1}
set ::env(GLB_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(GLB_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_HOLD_SLACK_MARGIN) {0.05}
set ::env(GLB_RESIZER_MAX_CAP_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_SLEW_MARGIN) {10}
set ::env(GLB_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(GLB_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(GLB_RESIZER_SETUP_SLACK_MARGIN) {0.025}
set ::env(GLB_RESIZER_TIMING_OPTIMIZATIONS) {1}
set ::env(GLOBAL_ROUTER) {fastroute}
set ::env(GND_PIN) {VSS}
set ::env(GPIO_PADS_LEF) { /home/passant/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_io/lef/GF018green_ipio_5p0c_75_5lm.lef
}
set ::env(GPIO_PADS_VERILOG) { /home/passant/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_io/verilog/GF018green_ipio_5p0c_75_5lm.v
}
set ::env(GPL_CELL_PADDING) {0}
set ::env(GRT_ADJUSTMENT) {0.3}
set ::env(GRT_ALLOW_CONGESTION) {0}
set ::env(GRT_ANT_ITERS) {3}
set ::env(GRT_ESTIMATE_PARASITICS) {1}
set ::env(GRT_LAYER_ADJUSTMENTS) {0,0,0,0,0}
set ::env(GRT_MACRO_EXTENSION) {0}
set ::env(GRT_MAX_DIODE_INS_ITERS) {1}
set ::env(GRT_OVERFLOW_ITERS) {50}
set ::env(IO_PCT) {0.2}
set ::env(KLAYOUT_DRC_KLAYOUT_GDS) {0}
set ::env(KLAYOUT_DRC_TECH_SCRIPT) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/klayout/gf180mcuC_mr.drc}
set ::env(KLAYOUT_PROPERTIES) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/klayout/gf180mcuC.lyp}
set ::env(KLAYOUT_TECH) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/klayout/gf180mcuC.lyt}
set ::env(KLAYOUT_XOR_GDS) {1}
set ::env(KLAYOUT_XOR_XML) {1}
set ::env(LEC_ENABLE) {0}
set ::env(LEFT_MARGIN_MULT) {12}
set ::env(LIB_FASTEST) {/home/passant/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/liberty/gf180mcu_fd_sc_mcu7t5v0__ff_n40C_5v50.lib}
set ::env(LIB_SLOWEST) {/home/passant/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/liberty/gf180mcu_fd_sc_mcu7t5v0__ss_125C_4v50.lib}
set ::env(LIB_SYNTH) {/home/passant/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/liberty/gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00.lib}
set ::env(LIB_TYPICAL) {/home/passant/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/liberty/gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00.lib}
set ::env(LOGS_DIR) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/logs}
set ::env(LVS_CONNECT_BY_LABEL) {0}
set ::env(LVS_INSERT_POWER_PINS) {1}
set ::env(MACRO_BLOCKAGES_LAYER) {Metal1 Metal2 Metal3 Metal4 Metal5}
set ::env(MAGIC_CONVERT_DRC_TO_RDB) {1}
set ::env(MAGIC_DEF_LABELS) {1}
set ::env(MAGIC_DEF_NO_BLOCKAGES) {1}
set ::env(MAGIC_DISABLE_HIER_GDS) {1}
set ::env(MAGIC_DRC_USE_GDS) {1}
set ::env(MAGIC_EXT_USE_GDS) {0}
set ::env(MAGIC_GDS_ALLOW_ABSTRACT) {0}
set ::env(MAGIC_GENERATE_GDS) {1}
set ::env(MAGIC_GENERATE_LEF) {1}
set ::env(MAGIC_GENERATE_MAGLEF) {1}
set ::env(MAGIC_INCLUDE_GDS_POINTERS) {0}
set ::env(MAGIC_MAGICRC) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/magic/gf180mcuC.magicrc}
set ::env(MAGIC_PAD) {0}
set ::env(MAGIC_TECH_FILE) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/magic/gf180mcuC.tech}
set ::env(MAGIC_WRITE_FULL_LEF) {0}
set ::env(MAGIC_ZEROIZE_ORIGIN) {0}
set ::env(METAL_LAYER_NAMES) {Metal1 Metal2 Metal3 Metal4 Metal5}
set ::env(NETGEN_SETUP_FILE) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/netgen/gf180mcuC_setup.tcl}
set ::env(NO_SYNTH_CELL_LIST) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/no_synth.cells}
set ::env(OPENLANE_VERBOSE) {0}
set ::env(PDKPATH) {/home/passant/OpenLane/pdks/gf180mcuC}
set ::env(PDN_CFG) {/openlane/scripts/openroad/common/pdn_cfg.tcl}
set ::env(PLACE_SITE) {GF018hv5v_mcu_sc7}
set ::env(PLACE_SITE_HEIGHT) {3.92}
set ::env(PLACE_SITE_WIDTH) {0.56}
set ::env(PL_BASIC_PLACEMENT) {0}
set ::env(PL_ESTIMATE_PARASITICS) {1}
set ::env(PL_LIB) {/home/passant/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/liberty/gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00.lib}
set ::env(PL_MACRO_CHANNEL) {0 0}
set ::env(PL_MACRO_HALO) {0 0}
set ::env(PL_MAX_DISPLACEMENT_X) {500}
set ::env(PL_MAX_DISPLACEMENT_Y) {100}
set ::env(PL_OPTIMIZE_MIRRORING) {1}
set ::env(PL_RANDOM_GLB_PLACEMENT) {0}
set ::env(PL_RANDOM_INITIAL_PLACEMENT) {0}
set ::env(PL_RESIZER_ALLOW_SETUP_VIOS) {0}
set ::env(PL_RESIZER_BUFFER_INPUT_PORTS) {1}
set ::env(PL_RESIZER_BUFFER_OUTPUT_PORTS) {1}
set ::env(PL_RESIZER_DESIGN_OPTIMIZATIONS) {1}
set ::env(PL_RESIZER_HOLD_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_HOLD_SLACK_MARGIN) {0.1}
set ::env(PL_RESIZER_MAX_CAP_MARGIN) {20}
set ::env(PL_RESIZER_MAX_SLEW_MARGIN) {20}
set ::env(PL_RESIZER_MAX_WIRE_LENGTH) {0}
set ::env(PL_RESIZER_REPAIR_TIE_FANOUT) {1}
set ::env(PL_RESIZER_SETUP_MAX_BUFFER_PERCENT) {50}
set ::env(PL_RESIZER_SETUP_SLACK_MARGIN) {0.05}
set ::env(PL_RESIZER_TIE_SEPERATION) {0}
set ::env(PL_RESIZER_TIMING_OPTIMIZATIONS) {1}
set ::env(PL_ROUTABILITY_DRIVEN) {1}
set ::env(PL_SKIP_INITIAL_PLACEMENT) {0}
set ::env(PL_TARGET_DENSITY) {0.55}
set ::env(PL_TIME_DRIVEN) {1}
set ::env(PRIMARY_SIGNOFF_TOOL) {magic}
set ::env(PROCESS) {180}
set ::env(QUIT_ON_HOLD_VIOLATIONS) {1}
set ::env(QUIT_ON_ILLEGAL_OVERLAPS) {1}
set ::env(QUIT_ON_LONG_WIRE) {0}
set ::env(QUIT_ON_LVS_ERROR) {1}
set ::env(QUIT_ON_MAGIC_DRC) {1}
set ::env(QUIT_ON_SETUP_VIOLATIONS) {1}
set ::env(QUIT_ON_TIMING_VIOLATIONS) {1}
set ::env(QUIT_ON_TR_DRC) {1}
set ::env(RCX_CC_MODEL) {10}
set ::env(RCX_CONTEXT_DEPTH) {5}
set ::env(RCX_CORNER_COUNT) {1}
set ::env(RCX_COUPLING_THRESHOLD) {0.1}
set ::env(RCX_MAX_RESISTANCE) {50}
set ::env(RCX_MERGE_VIA_WIRE_RES) {1}
set ::env(RCX_RULES) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/openlane/rules.openrcx.gf180mcuC.nom}
set ::env(RCX_RULES_MAX) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/openlane/rules.openrcx.gf180mcuC.max}
set ::env(RCX_RULES_MIN) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/openlane/rules.openrcx.gf180mcuC.min}
set ::env(REPORTS_DIR) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/reports}
set ::env(RESULTS_DIR) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/results}
set ::env(RIGHT_MARGIN_MULT) {12}
set ::env(RIPPLE_CARRY_ADDER_MAP) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/rca_map.v}
set ::env(ROUTING_CORES) {2}
set ::env(RSZ_DONT_TOUCH_RX) {$^}
set ::env(RSZ_USE_OLD_REMOVER) {0}
set ::env(RT_MAX_LAYER) {Metal5}
set ::env(RT_MIN_LAYER) {Metal2}
set ::env(RUN_CVC) {1}
set ::env(RUN_DIR) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18}
set ::env(RUN_DRT) {1}
set ::env(RUN_FILL_INSERTION) {1}
set ::env(RUN_IRDROP_REPORT) {1}
set ::env(RUN_KLAYOUT) {0}
set ::env(RUN_KLAYOUT_DRC) {0}
set ::env(RUN_KLAYOUT_XOR) {0}
set ::env(RUN_LVS) {1}
set ::env(RUN_MAGIC) {1}
set ::env(RUN_MAGIC_DRC) {1}
set ::env(RUN_SPEF_EXTRACTION) {1}
set ::env(RUN_TAG) {22_12_14_04_18}
set ::env(RUN_TAP_DECAP_INSERTION) {1}
set ::env(SCLPATH) {/home/passant/OpenLane/pdks/gf180mcuC/gf180mcu_fd_sc_mcu7t5v0}
set ::env(SPEF_EXTRACTOR) {openrcx}
set ::env(START_TIME) {2022.12.14_12.18.11}
set ::env(STA_REPORT_POWER) {1}
set ::env(STA_WRITE_LIB) {1}
set ::env(STD_CELL_GROUND_PINS) {VSS VPW}
set ::env(STD_CELL_LIBRARY) {gf180mcu_fd_sc_mcu7t5v0}
set ::env(STD_CELL_LIBRARY_CDL) {/home/passant/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/cdl/gf180mcu_fd_sc_mcu7t5v0.cdl}
set ::env(STD_CELL_LIBRARY_OPT) {gf180mcu_fd_sc_mcu7t5v0}
set ::env(STD_CELL_POWER_PINS) {VDD VNW}
set ::env(SYNTH_ADDER_TYPE) {YOSYS}
set ::env(SYNTH_BIN) {yosys}
set ::env(SYNTH_BUFFERING) {1}
set ::env(SYNTH_CAP_LOAD) {72.91}
set ::env(SYNTH_CLK_DRIVING_CELL) {gf180mcu_fd_sc_mcu7t5v0__inv_4}
set ::env(SYNTH_CLK_DRIVING_CELL_PIN) {ZN}
set ::env(SYNTH_CLOCK_TRANSITION) {0.15}
set ::env(SYNTH_CLOCK_UNCERTAINTY) {0.25}
set ::env(SYNTH_DRIVING_CELL) {gf180mcu_fd_sc_mcu7t5v0__inv_1}
set ::env(SYNTH_DRIVING_CELL_PIN) {ZN}
set ::env(SYNTH_ELABORATE_ONLY) {0}
set ::env(SYNTH_EXTRA_MAPPING_FILE) {}
set ::env(SYNTH_FLAT_TOP) {0}
set ::env(SYNTH_LATCH_MAP) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/latch_map.v}
set ::env(SYNTH_MAX_FANOUT) {10}
set ::env(SYNTH_MIN_BUF_PORT) {gf180mcu_fd_sc_mcu7t5v0__buf_1 I Z}
set ::env(SYNTH_NO_FLAT) {0}
set ::env(SYNTH_READ_BLACKBOX_LIB) {1}
set ::env(SYNTH_SCRIPT) {/openlane/scripts/yosys/synth.tcl}
set ::env(SYNTH_SHARE_RESOURCES) {1}
set ::env(SYNTH_SIZING) {0}
set ::env(SYNTH_STRATEGY) {AREA 0}
set ::env(SYNTH_TIEHI_PORT) {gf180mcu_fd_sc_mcu7t5v0__tieh Z}
set ::env(SYNTH_TIELO_PORT) {gf180mcu_fd_sc_mcu7t5v0__tiel ZN}
set ::env(SYNTH_TIMING_DERATE) {0.05}
set ::env(TAKE_LAYOUT_SCROT) {0}
set ::env(TECH_LEF) {/home/passant/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/techlef/gf180mcu_fd_sc_mcu7t5v0__nom.tlef}
set ::env(TECH_LEF_MAX) {/home/passant/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/techlef/gf180mcu_fd_sc_mcu7t5v0__max.tlef}
set ::env(TECH_LEF_MIN) {/home/passant/OpenLane/pdks/gf180mcuC/libs.ref/gf180mcu_fd_sc_mcu7t5v0/techlef/gf180mcu_fd_sc_mcu7t5v0__min.tlef}
set ::env(TERMINAL_OUTPUT) {/dev/null}
set ::env(TMP_DIR) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/tmp}
set ::env(TOP_MARGIN_MULT) {4}
set ::env(TRACKS_INFO_FILE) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/tracks.info}
set ::env(TRISTATE_BUFFER_MAP) {/home/passant/OpenLane/pdks/gf180mcuC/libs.tech/openlane/gf180mcu_fd_sc_mcu7t5v0/tribuff_map.v}
set ::env(USE_ARC_ANTENNA_CHECK) {1}
set ::env(USE_GPIO_PADS) {0}
set ::env(VDD_PIN) {VDD}
set ::env(VERILOG_FILES) { /home/passant/caravel-gf180mcu/verilog//rtl/user_defines.v  /home/passant/caravel-gf180mcu/verilog//rtl/defines.v  /home/passant/caravel-gf180mcu/verilog//rtl/chip_io.v  }
set ::env(WIRE_RC_LAYER) {Metal2}
set ::env(YOSYS_REWRITE_VERILOG) {0}
set ::env(cts_logs) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/logs/cts}
set ::env(cts_reports) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/reports/cts}
set ::env(cts_results) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/results/cts}
set ::env(cts_tmpfiles) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/tmp/cts}
set ::env(eco_logs) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/logs/eco}
set ::env(eco_reports) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/reports/eco}
set ::env(eco_results) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/results/eco}
set ::env(eco_tmpfiles) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/tmp/eco}
set ::env(floorplan_logs) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/logs/floorplan}
set ::env(floorplan_reports) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/reports/floorplan}
set ::env(floorplan_results) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/results/floorplan}
set ::env(floorplan_tmpfiles) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/tmp/floorplan}
set ::env(placement_logs) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/logs/placement}
set ::env(placement_reports) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/reports/placement}
set ::env(placement_results) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/results/placement}
set ::env(placement_tmpfiles) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/tmp/placement}
set ::env(routing_logs) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/logs/routing}
set ::env(routing_reports) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/reports/routing}
set ::env(routing_results) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/results/routing}
set ::env(routing_tmpfiles) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/tmp/routing}
set ::env(signoff_logs) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/logs/signoff}
set ::env(signoff_reports) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/reports/signoff}
set ::env(signoff_results) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/results/signoff}
set ::env(signoff_tmpfiles) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/tmp/signoff}
set ::env(synthesis_logs) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/logs/synthesis}
set ::env(synthesis_reports) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/reports/synthesis}
set ::env(synthesis_results) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/results/synthesis}
set ::env(synthesis_tmpfiles) {/home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/tmp/synthesis}
set ::env(SYNTH_MAX_TRAN) {1.0}
set ::env(CURRENT_INDEX) 0
set ::env(CURRENT_DEF) {0}
set ::env(CURRENT_GUIDE) {0}
set ::env(CURRENT_NETLIST) /home/passant/caravel-gf180mcu/openlane/chip_io/runs/22_12_14_04_18/results/synthesis/chip_io.v
set ::env(CURRENT_POWERED_NETLIST) {0}
set ::env(CURRENT_ODB) {0}
